export type RevenueFact = {
  period: string;
  value: string;
  scope: string;
  sourceIds: string[];
};

export type DiligenceSource = {
  id: string;
  label: string;
  url: string;
};

export type AssetDiligence = {
  ownership: "Public parent" | "Private";
  parent: string;
  rightsHolder: string;
  ticker?: string;
  companyUrl: string;
  latestDisplay: string;
  latestPeriod: string;
  sortUsdMm: number | null;
  disclosure: "Exact U.S." | "Broader disclosure" | "Not disclosed" | "Pre-revenue";
  launch: string;
  indicationSplit: string;
  revenueFacts: RevenueFact[];
  notes: string[];
  sources: DiligenceSource[];
};

export const TOP20_DILIGENCE: Record<string, AssetDiligence> = {
  "specialty-tryvio": {
    ownership: "Public parent",
    parent: "Idorsia Ltd",
    rightsHolder: "Idorsia Pharmaceuticals US Inc.",
    ticker: "SIX: IDIA",
    companyUrl: "https://www.idorsia.us/",
    latestDisplay: "Not disclosed",
    latestPeriod: "FY2025 U.S. annual",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: October 2024",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "H1 2025", value: "CHF 0.122m", scope: "TRYVIO net product sales; interim period, not annualized", sourceIds: ["id-25h1"] },
    ],
    notes: ["Idorsia did not separately report a full-year 2025 U.S. TRYVIO figure.", "No estimate or annualized value is shown."],
    sources: [
      { id: "id-25h1", label: "Idorsia H1 2025 financial report", url: "https://www.idorsia.com/dam/jcr%3A522b3316-b8e9-4a5d-b979-a0aaec90d2cb/2025-6m-idorsia-financial-report.pdf" },
      { id: "id-25ar", label: "Idorsia 2025 annual report", url: "https://www.idorsia.com/dam/jcr%3A661f2eb2-71c7-4d59-8b66-f47ba10aefc2/2025_idorsia-annual-report.pdf" },
    ],
  },
  "specialty-qbrexza": {
    ownership: "Public parent",
    parent: "Journey Medical Corporation",
    rightsHolder: "Journey Medical Corporation",
    ticker: "NASDAQ: DERM",
    companyUrl: "https://www.journeymedicalcorp.com/",
    latestDisplay: "$25.014m",
    latestPeriod: "FY2025 U.S. net product revenue",
    sortUsdMm: 25.014,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: 2018; Journey began sales in Q2 2021",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$25.014m", scope: "U.S. net product revenue", sourceIds: ["jm-25"] },
      { period: "2024", value: "$25.114m", scope: "U.S. net product revenue", sourceIds: ["jm-25", "jm-24"] },
      { period: "2023", value: "$25.410m", scope: "U.S. net product revenue", sourceIds: ["jm-24", "jm-23"] },
      { period: "2022", value: "$26.715m", scope: "U.S. net product revenue", sourceIds: ["jm-23", "jm-22"] },
      { period: "2021", value: "$17.056m", scope: "Journey period after Q2 2021 acquisition", sourceIds: ["jm-22"] },
    ],
    notes: ["2018–2020 product sales were under the prior owner and are not separately reported in Journey's filings."],
    sources: [
      { id: "jm-25", label: "Journey 2025 Form 10-K", url: "https://ir.journeymedicalcorp.com/financials/sec-filings/content/0001104659-26-034629/derm-20251231x10k.htm" },
      { id: "jm-24", label: "Journey 2024 Form 10-K", url: "https://ir.journeymedicalcorp.com/financials/sec-filings/content/0001410578-25-000490/derm-20241231x10k.htm" },
      { id: "jm-23", label: "Journey 2023 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867066/000141057824000347/derm-20231231x10k.htm" },
      { id: "jm-22", label: "Journey 2022 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867066/000141057823000485/derm-20221231x10k.htm" },
    ],
  },
  "specialty-rayaldee": {
    ownership: "Public parent",
    parent: "OPKO Health, Inc.",
    rightsHolder: "OPKO Pharmaceuticals, LLC",
    ticker: "NASDAQ: OPK",
    companyUrl: "https://www.opko.com/",
    latestDisplay: "$29.8m",
    latestPeriod: "FY2025 U.S. net product revenue",
    sortUsdMm: 29.8,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: November 2016",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$29.8m", scope: "U.S. net product revenue", sourceIds: ["opko-25"] },
      { period: "2024", value: "$29.0m", scope: "U.S. net product revenue", sourceIds: ["opko-25", "opko-24"] },
      { period: "2023", value: "$31.0m", scope: "U.S. net product revenue", sourceIds: ["opko-24"] },
      { period: "2022", value: "$27.3m", scope: "U.S. net product revenue", sourceIds: ["opko-24"] },
      { period: "2021", value: "$27.0m", scope: "U.S. net product revenue", sourceIds: ["opko-21"] },
      { period: "2020", value: "$36.8m", scope: "U.S. net product revenue", sourceIds: ["opko-21"] },
      { period: "2019", value: "$31.4m", scope: "U.S. net product revenue", sourceIds: ["opko-20"] },
      { period: "2018", value: "$20.3m", scope: "U.S. net product revenue", sourceIds: ["opko-18"] },
      { period: "2017", value: "$9.1m", scope: "U.S. net product revenue; included previously deferred launch shipments", sourceIds: ["opko-17", "opko-18"] },
    ],
    notes: ["No 2016 revenue was recognized; $1.6m of launch shipments was deferred."],
    sources: [
      { id: "opko-25", label: "OPKO FY2025 results", url: "https://www.opko.com/investors/news-events/press-releases/detail/538/opko-health-reports-fourth-quarter-2025-business-highlights-and-financial-results" },
      { id: "opko-24", label: "OPKO 2024 Form 10-K", url: "https://www.opko.com/investors/sec-filings/all-sec-filings/content/0001437749-25-005811/opk20241231_10k.htm" },
      { id: "opko-21", label: "OPKO 2021 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/944809/000094480922000009/opk-20211231.htm" },
      { id: "opko-20", label: "OPKO 2020 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/944809/000094480921000015/opk-20201231.htm" },
      { id: "opko-18", label: "OPKO 2018 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/944809/000094480919000017/opk-12312018x10k.htm" },
      { id: "opko-17", label: "OPKO 2017 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/944809/000094480918000014/opk-12312017x10k.htm" },
    ],
  },
  "specialty-inpefa": {
    ownership: "Public parent",
    parent: "Lexicon Pharmaceuticals, Inc.",
    rightsHolder: "Lexicon Pharmaceuticals, Inc.",
    ticker: "NASDAQ: LXRX",
    companyUrl: "https://www.lexpharma.com/",
    latestDisplay: "$4.647m",
    latestPeriod: "FY2025 U.S. net product revenue",
    sortUsdMm: 4.647,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: June 2023",
    indicationSplit: "No indication-level revenue split disclosed.",
    revenueFacts: [
      { period: "2025", value: "$4.647m", scope: "U.S. net product revenue", sourceIds: ["lx-25"] },
      { period: "2024", value: "$6.0m", scope: "U.S. net product revenue", sourceIds: ["lx-25"] },
      { period: "2023", value: "$1.2m", scope: "U.S. net product revenue after June launch", sourceIds: ["lx-23"] },
    ],
    notes: ["Lexicon reports product revenue for INPEFA but does not split it by labeled patient subgroup."],
    sources: [
      { id: "lx-25", label: "Lexicon 2025 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1062822/000106282226000050/lxrx-20251231.htm" },
      { id: "lx-23", label: "Lexicon 2023 annual report", url: "https://www.sec.gov/Archives/edgar/data/1062822/000106282224000018/annualreport-march2024.pdf" },
    ],
  },
  "specialty-ameluz-rhodoled": {
    ownership: "Public parent",
    parent: "Biofrontera Inc.",
    rightsHolder: "Biofrontera Inc.",
    ticker: "NASDAQ: BFRI",
    companyUrl: "https://www.biofrontera-us.com/",
    latestDisplay: "$41.705m",
    latestPeriod: "FY2025 company product revenue",
    sortUsdMm: 41.705,
    disclosure: "Broader disclosure",
    launch: "U.S. launch: October 2016",
    indicationSplit: "No indication-level revenue split disclosed.",
    revenueFacts: [
      { period: "2025", value: "$41.705m", scope: "Company net product revenue; issuer states Ameluz and lamps were approximately 100%", sourceIds: ["bf-25"] },
      { period: "2024", value: "$37.303m", scope: "Company net product revenue; not separately product-specific", sourceIds: ["bf-25", "bf-24"] },
      { period: "2023", value: "$34.005m", scope: "Company net product revenue; not separately product-specific", sourceIds: ["bf-24"] },
      { period: "2022", value: "$28.5m", scope: "Company net product revenue; increase primarily driven by Ameluz", sourceIds: ["bf-22"] },
      { period: "2021", value: "$24.0m", scope: "Company net product revenue; not separately product-specific", sourceIds: ["bf-22"] },
      { period: "2020", value: "$18.8m", scope: "Company net product revenue; not separately product-specific", sourceIds: ["bf-20"] },
    ],
    notes: ["Biofrontera Inc. completed acquisition of all U.S. Ameluz and RhodoLED rights in October 2025.", "Earlier company filings include other products and do not provide a clean asset-only series."],
    sources: [
      { id: "bf-25", label: "Biofrontera 2025 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1858685/000149315226011625/form10-k.htm" },
      { id: "bf-24", label: "Biofrontera 2024 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1858685/000149315225011052/form10-k.htm" },
      { id: "bf-22", label: "Biofrontera 2022 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1858685/000149315223007472/form10-k.htm" },
      { id: "bf-20", label: "Biofrontera 2021 registration statement", url: "https://www.sec.gov/Archives/edgar/data/1858685/000149315222009524/form424b3.htm" },
      { id: "bf-rights", label: "U.S. rights acquisition filing", url: "https://www.sec.gov/Archives/edgar/data/1858685/000164117225017285/form8-k.htm" },
    ],
  },
  "specialty-mycapssa": {
    ownership: "Private",
    parent: "Chiesi Farmaceutici S.p.A.",
    rightsHolder: "Chiesi USA, Inc.",
    companyUrl: "https://chiesirarediseases.com/",
    latestDisplay: "Not disclosed",
    latestPeriod: "U.S. annual product revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: September 2020; Chiesi acquisition closed June 2022",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [],
    notes: ["Chiesi is privately held and does not publicly report U.S. MYCAPSSA annual revenue."],
    sources: [
      { id: "ch-products", label: "Chiesi U.S. rare-disease products", url: "https://chiesirarediseases.com/products" },
      { id: "ch-results", label: "Chiesi FY2025 company results", url: "https://www.chiesi.com/en/media-hub/press-releases/chiesi-reports-strong-fy2025-financial-sustainability-results" },
    ],
  },
  "specialty-cuvrior": {
    ownership: "Private",
    parent: "Orphalan SA",
    rightsHolder: "Orphalan, Inc.",
    companyUrl: "https://www.orphalan.com/",
    latestDisplay: "Not disclosed",
    latestPeriod: "U.S. annual product revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: April 2023",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [],
    notes: ["Orphalan is privately held and does not publicly report U.S. CUVRIOR annual revenue."],
    sources: [
      { id: "or-launch", label: "Orphalan U.S. commercial launch", url: "https://www.orphalan.com/orphalan-announces-us-commercial-launch-of-cuvrior-for-the-treatment-of-wilson-disease/" },
      { id: "or-us", label: "Orphalan corporate site", url: "https://www.orphalan.com/" },
    ],
  },
  "specialty-lodoco": {
    ownership: "Private",
    parent: "AGEPHA Pharma s.r.o.",
    rightsHolder: "AGEPHA Pharma USA, LLC",
    companyUrl: "https://us.agephapharma.com/",
    latestDisplay: "Not disclosed",
    latestPeriod: "U.S. annual product revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: 2023",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [],
    notes: ["AGEPHA is privately held and does not publicly report U.S. LODOCO annual revenue."],
    sources: [
      { id: "ag-approval", label: "AGEPHA U.S. approval statement", url: "https://us.agephapharma.com/blog/2023/06/20/us-fda-approves-first-anti-inflammatory-drug-for-cardiovascular-disease/" },
      { id: "ag-us", label: "AGEPHA Pharma USA", url: "https://us.agephapharma.com/" },
    ],
  },
  "specialty-secuado": {
    ownership: "Public parent",
    parent: "Hisamitsu Pharmaceutical Co., Inc.",
    rightsHolder: "Noven Therapeutics, LLC",
    ticker: "TSE: 4530",
    companyUrl: "https://www.noven.com/",
    latestDisplay: "Not disclosed",
    latestPeriod: "U.S. annual product revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: 2020",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [],
    notes: ["Hisamitsu does not separately report U.S. SECUADO annual revenue."],
    sources: [
      { id: "nv-product", label: "Noven SECUADO product page", url: "https://www.noven.com/secuado/" },
      { id: "nv-parent", label: "Noven parent-company profile", url: "https://www.noven.com/about/parent-company/" },
      { id: "hs-ir", label: "Hisamitsu investor reports", url: "https://global.hisamitsu/ir/library/annual.html" },
    ],
  },
  "specialty-crexont": {
    ownership: "Public parent",
    parent: "Amneal Pharmaceuticals, Inc.",
    rightsHolder: "Amneal Pharmaceuticals, Inc.",
    ticker: "NASDAQ: AMRX",
    companyUrl: "https://www.amneal.com/",
    latestDisplay: "Not disclosed",
    latestPeriod: "U.S. annual product revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: "U.S. launch: September 2024",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [],
    notes: ["Amneal discusses CREXONT as a specialty-segment growth driver but does not report annual product revenue separately."],
    sources: [
      { id: "am-25", label: "Amneal FY2025 results", url: "https://investors.amneal.com/news/press-releases/press-release-details/2026/Amneal-Reports-Fourth-Quarter-and-Full-Year-2025-Financial-Results/default.aspx" },
      { id: "am-product", label: "Amneal U.S. CREXONT access update", url: "https://investors.amneal.com/news/press-releases/press-release-details/2025/Amneal-Announces-Expanded-Coverage-for-CREXONT-Carbidopa-and-Levodopa-to-Enhance-Access-for-Parkinsons-Disease-Patients-in-the-U-S-/default.aspx" },
    ],
  },
  "specialty-igalmi": {
    ownership: "Public parent",
    parent: "BioXcel Therapeutics, Inc.",
    rightsHolder: "BioXcel Therapeutics, Inc.",
    ticker: "NASDAQ: BTAI",
    companyUrl: "https://www.bioxceltherapeutics.com/",
    latestDisplay: "$0.642m",
    latestPeriod: "FY2025 U.S. net product revenue",
    sortUsdMm: 0.642,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: July 2022",
    indicationSplit: "Indication-level revenue split not disclosed.",
    revenueFacts: [
      { period: "2025", value: "$0.642m", scope: "U.S. net product revenue", sourceIds: ["bx-25"] },
      { period: "2024", value: "$2.266m", scope: "U.S. net product revenue", sourceIds: ["bx-24"] },
      { period: "2023", value: "$1.380m", scope: "U.S. net product revenue", sourceIds: ["bx-23", "bx-24"] },
      { period: "2022", value: "$0.375m", scope: "U.S. net product revenue after July launch", sourceIds: ["bx-23"] },
    ],
    notes: ["IGALMI was BioXcel's only commercial product during these periods."],
    sources: [
      { id: "bx-25", label: "BioXcel FY2025 results", url: "https://ir.bioxceltherapeutics.com/news-releases/news-release-details/bioxcel-therapeutics-reports-fourth-quarter-and-full-year-2025" },
      { id: "bx-24", label: "BioXcel 2024 annual report", url: "https://www.sec.gov/Archives/edgar/data/1720893/000110465925110500/tm2510950d2_ars.pdf" },
      { id: "bx-23", label: "BioXcel 2023 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1720893/000155837024003784/btai-20231231x10k.htm" },
    ],
  },
  "specialty-gvoke": {
    ownership: "Public parent",
    parent: "Xeris Biopharma Holdings, Inc.",
    rightsHolder: "Xeris Pharmaceuticals, Inc.",
    ticker: "NASDAQ: XERS",
    companyUrl: "https://www.xerispharma.com/",
    latestDisplay: "$94.108m",
    latestPeriod: "FY2025 U.S. net product sales",
    sortUsdMm: 94.108,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: November 2019",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$94.108m", scope: "U.S. net product sales", sourceIds: ["xr-25"] },
      { period: "2024", value: "$82.829m", scope: "U.S. net product sales", sourceIds: ["xr-24", "xr-25"] },
      { period: "2023", value: "$67.045m", scope: "U.S. net product sales", sourceIds: ["xr-23", "xr-24"] },
      { period: "2022", value: "$52.527m", scope: "U.S. net product sales", sourceIds: ["xr-22", "xr-23"] },
      { period: "2021", value: "$38.917m", scope: "U.S. net product sales", sourceIds: ["xr-22"] },
      { period: "2020", value: "$20.2m", scope: "U.S. net product sales", sourceIds: ["xr-20"] },
      { period: "2019", value: "$1.6m", scope: "U.S. net product sales after November launch", sourceIds: ["xr-20"] },
    ],
    notes: [],
    sources: [
      { id: "xr-25", label: "Xeris FY2025 results", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709626000012/exh991q42025earningsrelease.htm" },
      { id: "xr-24", label: "Xeris 2024 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709625000039/xers-20241231.htm" },
      { id: "xr-23", label: "Xeris 2023 annual report", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709624000057/a2023annualreport.pdf" },
      { id: "xr-22", label: "Xeris 2022 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709623000031/xers-20221231.htm" },
      { id: "xr-20", label: "Xeris 2020 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1346302/000134630221000026/xers-20201231.htm" },
    ],
  },
  "specialty-keveyis": {
    ownership: "Public parent",
    parent: "Xeris Biopharma Holdings, Inc.",
    rightsHolder: "Xeris Pharmaceuticals, Inc.",
    ticker: "NASDAQ: XERS",
    companyUrl: "https://www.xerispharma.com/",
    latestDisplay: "$47.649m",
    latestPeriod: "FY2025 U.S. net product sales",
    sortUsdMm: 47.649,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: April 2017; Xeris acquisition closed October 2021",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$47.649m", scope: "U.S. net product sales", sourceIds: ["xr-25"] },
      { period: "2024", value: "$49.530m", scope: "U.S. net product sales", sourceIds: ["xr-24", "xr-25"] },
      { period: "2023", value: "$56.772m", scope: "U.S. net product sales", sourceIds: ["xr-23", "xr-24"] },
      { period: "2022", value: "$49.307m", scope: "U.S. net product sales", sourceIds: ["xr-22", "xr-23"] },
      { period: "2021", value: "$38–40m", scope: "Full-year pro forma net revenue range disclosed by Xeris", sourceIds: ["xr-21"] },
      { period: "2020", value: "$30.670m", scope: "U.S. net product sales under Strongbridge", sourceIds: ["sb-20"] },
      { period: "2019", value: "$21.676m", scope: "U.S. net product sales under Strongbridge", sourceIds: ["sb-20", "sb-19"] },
      { period: "2018", value: "$16.802m", scope: "U.S. net product sales under Strongbridge", sourceIds: ["sb-20", "sb-19"] },
      { period: "2017", value: "$7.046m", scope: "U.S. net product sales after April launch", sourceIds: ["sb-19"] },
    ],
    notes: ["The 2021 filing gives a reported range, not an exact full-year figure; it is shown as reported and not midpointed."],
    sources: [
      { id: "xr-25", label: "Xeris FY2025 results", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709626000012/exh991q42025earningsrelease.htm" },
      { id: "xr-24", label: "Xeris 2024 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709625000039/xers-20241231.htm" },
      { id: "xr-23", label: "Xeris 2023 annual report", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709624000057/a2023annualreport.pdf" },
      { id: "xr-22", label: "Xeris 2022 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709623000031/xers-20221231.htm" },
      { id: "xr-21", label: "Xeris FY2021 results", url: "https://www.sec.gov/Archives/edgar/data/1867096/000186709622000033/exh991q42021earningsrelease.htm" },
      { id: "sb-20", label: "Strongbridge 2020 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1634432/000155837021002288/sbbp-20201231x10k.htm" },
      { id: "sb-19", label: "Strongbridge 2019 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1634432/000155837020001720/sbbp-20191231x10k.htm" },
    ],
  },
  "specialty-afrezza": {
    ownership: "Public parent",
    parent: "MannKind Corporation",
    rightsHolder: "MannKind Corporation",
    ticker: "NASDAQ: MNKD",
    companyUrl: "https://www.mannkindcorp.com/",
    latestDisplay: "$74.587m",
    latestPeriod: "FY2025 global product net revenue",
    sortUsdMm: null,
    disclosure: "Broader disclosure",
    launch: "U.S. launch: February 2015; MannKind resumed direct distribution July 2016",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$74.587m", scope: "Global AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-25"] },
      { period: "2024", value: "$64.041m", scope: "Global AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-25"] },
      { period: "2023", value: "$54.914m", scope: "Global AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-25"] },
      { period: "2022", value: "$43.316m", scope: "AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-22"] },
      { period: "2021", value: "$39.168m", scope: "AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-22"] },
      { period: "2020", value: "$32.324m", scope: "AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-22"] },
      { period: "2019", value: "$25.304m", scope: "AFREZZA product net revenue; includes $0.7m Brazil", sourceIds: ["mk-19"] },
      { period: "2018", value: "$17.276m", scope: "AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-19"] },
      { period: "2017", value: "$9.2m", scope: "AFREZZA product net revenue; U.S. split not disclosed", sourceIds: ["mk-18"] },
      { period: "2016", value: "$1.9m", scope: "MannKind commercial product revenue after July distribution restart", sourceIds: ["mk-16"] },
    ],
    notes: ["MannKind reports AFREZZA product revenue but does not publish a consistent U.S.-only annual series.", "Sanofi commercialization-period market revenue for 2015 is not separately disclosed in MannKind's filing."],
    sources: [
      { id: "mk-25", label: "MannKind 2025 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/899460/000119312526073516/mnkd-20251231.htm" },
      { id: "mk-22", label: "MannKind 2022 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/899460/000156459023002309/mnkd-10k_20221231.htm" },
      { id: "mk-19", label: "MannKind 2019 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/899460/000156459020006198/mnkd-10k_20191231.htm" },
      { id: "mk-18", label: "MannKind FY2018 results", url: "https://www.sec.gov/Archives/edgar/data/899460/000156459019004261/mnkd-ex991_6.htm" },
      { id: "mk-16", label: "MannKind 2016 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/899460/000119312517085519/d305327d10k.htm" },
    ],
  },
  "specialty-quviviq": {
    ownership: "Public parent",
    parent: "Idorsia Ltd",
    rightsHolder: "Idorsia Pharmaceuticals US Inc.",
    ticker: "SIX: IDIA",
    companyUrl: "https://www.idorsia.us/",
    latestDisplay: "CHF 28.6m",
    latestPeriod: "FY2024 exact U.S. net sales",
    sortUsdMm: null,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: May 2022",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "CHF 134m", scope: "Global QUVIVIQ net sales; U.S. split not disclosed", sourceIds: ["id-25"] },
      { period: "2024", value: "CHF 28.6m", scope: "Exact U.S. net sales", sourceIds: ["id-24"] },
      { period: "2023", value: "CHF 30.9m", scope: "Global QUVIVIQ net sales; U.S. split not disclosed", sourceIds: ["id-23"] },
      { period: "2022", value: "CHF 6.5m", scope: "Global QUVIVIQ net sales after launches in U.S., Germany and Italy", sourceIds: ["id-22"] },
    ],
    notes: ["The latest exact U.S. annual figure located is FY2024; FY2025 is reported only globally."],
    sources: [
      { id: "id-25", label: "Idorsia FY2025 results", url: "https://www.idorsia.com/investors/news-and-events/media-releases/media-release-details?id=3632613" },
      { id: "id-24", label: "Idorsia 2024 business report", url: "https://www.idorsia.com/dam/jcr%3Abf95f8e9-dfdf-4dbe-b223-257f3fb20969/2024_idorsia-annual-report-business.pdf" },
      { id: "id-23", label: "Idorsia 2023 financial report", url: "https://www.idorsia.com/dam/jcr%3Ad1df5c92-e415-47ee-b517-22d65e9c69f4/2023_idorsia-annual-report-finance.pdf" },
      { id: "id-22", label: "Idorsia FY2022 results", url: "https://www.idorsia.com/media/news/news-archive/media-release-details?id=2926547" },
    ],
  },
  "specialty-zypitamag": {
    ownership: "Public parent",
    parent: "Medicure Inc.",
    rightsHolder: "Medicure Pharma Inc.",
    ticker: "TSXV: MPH / OTC: MCUJF",
    companyUrl: "https://www.medicure.com/",
    latestDisplay: "C$6.5m",
    latestPeriod: "FY2025 U.S. product revenue",
    sortUsdMm: null,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: 2017; Medicure acquired ownership September 2019",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "C$6.5m", scope: "U.S. product revenue: C$2.8m insured + C$3.7m pharmacy channels", sourceIds: ["md-25"] },
      { period: "2024", value: "C$6.2m", scope: "U.S. product revenue: C$3.0m insured + C$3.2m Marley Drug", sourceIds: ["md-25", "md-24"] },
      { period: "2023", value: "C$5.0m", scope: "U.S. product revenue: C$2.4m insured + C$2.6m Marley Drug", sourceIds: ["md-24", "md-23"] },
      { period: "2022", value: "C$5.1m", scope: "Disclosed channel components: C$3.6m insured + C$1.5m Marley Drug", sourceIds: ["md-23", "md-22"] },
      { period: "2021", value: "C$3.2m", scope: "Traditional insured-channel revenue only; pharmacy-channel total not disclosed", sourceIds: ["md-22"] },
    ],
    notes: ["All values are reported in Canadian dollars; no currency conversion is applied."],
    sources: [
      { id: "md-25", label: "Medicure FY2025 results", url: "https://www.medicure.com/press-releases/medicure-reports-financial-results-for-the-year-ended-december-31-2025-and-schedules-april-27-2026-conference-call" },
      { id: "md-24", label: "Medicure FY2024 results", url: "https://www.medicure.com/press-releases/medicure-reports-financial-results-for-quarter-and-year-ended-december-31-2024" },
      { id: "md-23", label: "Medicure FY2023 results", url: "https://www.medicure.com/press-releases/medicure-reports-financial-results-for-quarter-and-year-ended-december-31-2023" },
      { id: "md-22", label: "Medicure FY2022 results", url: "https://www.medicure.com/press-releases/medicure-reports-financial-results-for-quarter-and-year-ended-december-31-2022" },
    ],
  },
  "specialty-savaysa": {
    ownership: "Public parent",
    parent: "Daiichi Sankyo Company, Limited",
    rightsHolder: "Daiichi Sankyo, Inc.",
    ticker: "TSE: 4568",
    companyUrl: "https://daiichisankyo.us/",
    latestDisplay: "JPY 1.4bn",
    latestPeriod: "FY2025 U.S. revenue",
    sortUsdMm: null,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: February 2015",
    indicationSplit: "No revenue split between the two approved indications.",
    revenueFacts: [
      { period: "FY2025", value: "JPY 1.4bn", scope: "U.S. revenue", sourceIds: ["ds-25"] },
      { period: "FY2024", value: "JPY 3.6bn", scope: "U.S. revenue", sourceIds: ["ds-25"] },
      { period: "FY2023", value: "JPY 2.4bn", scope: "U.S. revenue", sourceIds: ["ds-25"] },
      { period: "FY2022", value: "JPY 3.0bn", scope: "U.S. revenue", sourceIds: ["ds-25"] },
      { period: "FY2021", value: "JPY 1.9bn", scope: "U.S. revenue", sourceIds: ["ds-25"] },
      { period: "FY2020", value: "JPY 3.0bn", scope: "U.S. revenue", sourceIds: ["ds-20"] },
      { period: "FY2019", value: "JPY 2.6bn", scope: "U.S. revenue", sourceIds: ["ds-20"] },
      { period: "FY2018", value: "JPY 2.3bn", scope: "U.S. revenue", sourceIds: ["ds-18"] },
      { period: "FY2017", value: "JPY 2.2bn", scope: "U.S. revenue", sourceIds: ["ds-18"] },
      { period: "FY2016", value: "JPY 1.9bn", scope: "U.S. revenue", sourceIds: ["ds-18"] },
      { period: "FY2015", value: "JPY 0.4bn", scope: "U.S. revenue", sourceIds: ["ds-18"] },
      { period: "FY2014", value: "JPY 0.7bn", scope: "U.S. revenue after February launch", sourceIds: ["ds-18"] },
    ],
    notes: ["Daiichi Sankyo fiscal years end March 31. Values remain in reported yen; no currency conversion is applied."],
    sources: [
      { id: "ds-25", label: "Daiichi Sankyo FY2025 reference data", url: "https://www.daiichisankyo.com/files/investors/library/quarterly_result/2025/FY2025Q4_Reference_Data_E_v2.pdf" },
      { id: "ds-20", label: "Daiichi Sankyo FY2020 reference data", url: "https://www.daiichisankyo.com/files/investors/library/quarterly_result/2020/pdf/FY2020_Q4_Reference_Data_E.pdf" },
      { id: "ds-18", label: "Daiichi Sankyo historical reference data", url: "https://www.daiichisankyo.com/files/news/ir/pdf/005468/FY2019%20Q3%20Reference%20Data%20%28Corrected%20Version%29.pdf" },
    ],
  },
  "specialty-bysanti": {
    ownership: "Public parent",
    parent: "Vanda Pharmaceuticals Inc.",
    rightsHolder: "Vanda Pharmaceuticals Inc.",
    ticker: "NASDAQ: VNDA",
    companyUrl: "https://www.vandapharma.com/",
    latestDisplay: "No annual period",
    latestPeriod: "FDA approved February 2026",
    sortUsdMm: null,
    disclosure: "Pre-revenue",
    launch: "FDA approval: February 2026",
    indicationSplit: "No commercial revenue yet to split by indication.",
    revenueFacts: [],
    notes: ["No completed commercial year or product-specific revenue disclosure is available."],
    sources: [
      { id: "vd-news", label: "Vanda 2026 company news", url: "https://www.vandapharma.com/investors?current_news_page=2&current_quarter=2026" },
      { id: "vd-products", label: "Vanda products and pipeline", url: "https://www.vandapharma.com/products-and-pipeline" },
    ],
  },
  "specialty-belsomra": {
    ownership: "Public parent",
    parent: "Merck & Co., Inc.",
    rightsHolder: "Merck Sharp & Dohme LLC",
    ticker: "NYSE: MRK",
    companyUrl: "https://www.merck.com/",
    latestDisplay: "$82m",
    latestPeriod: "FY2025 U.S. sales",
    sortUsdMm: 82,
    disclosure: "Exact U.S.",
    launch: "U.S. launch: 2015",
    indicationSplit: "One approved indication; no split required.",
    revenueFacts: [
      { period: "2025", value: "$82m", scope: "U.S. sales", sourceIds: ["mrk-25"] },
      { period: "2024", value: "$72m", scope: "U.S. sales", sourceIds: ["mrk-24", "mrk-25"] },
      { period: "2023", value: "$81m", scope: "U.S. sales", sourceIds: ["mrk-24"] },
      { period: "2022", value: "$79m", scope: "U.S. sales", sourceIds: ["mrk-24"] },
    ],
    notes: ["Merck's located geographic product supplement provides the U.S. series from 2022; earlier public product totals are global and are not used as U.S. sales."],
    sources: [
      { id: "mrk-25", label: "Merck 4Q/FY2025 other financial disclosures", url: "https://www.merck.com/wp-content/uploads/sites/124/2026/02/4Q25-Merck-Other-Financial-Disclosures.pdf" },
      { id: "mrk-24", label: "Merck 2024 Form 10-K", url: "https://www.merck.com/wp-content/uploads/sites/152/2025/02/0001628280-25-007732.pdf" },
    ],
  },
  "specialty-hetlioz-hetlioz-lq": {
    ownership: "Public parent",
    parent: "Vanda Pharmaceuticals Inc.",
    rightsHolder: "Vanda Pharmaceuticals Inc.",
    ticker: "NASDAQ: VNDA",
    companyUrl: "https://www.vandapharma.com/",
    latestDisplay: "$71.4m",
    latestPeriod: "FY2025 franchise net product sales",
    sortUsdMm: null,
    disclosure: "Broader disclosure",
    launch: "U.S. launch: April 2014",
    indicationSplit: "No revenue split between Non-24 and Smith-Magenis syndrome.",
    revenueFacts: [
      { period: "2025", value: "$71.4m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-25"] },
      { period: "2024", value: "$76.675m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-24"] },
      { period: "2023", value: "$100.167m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-24"] },
      { period: "2022", value: "$159.655m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-22", "vd-24"] },
      { period: "2021", value: "$173.536m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-21", "vd-22"] },
      { period: "2020", value: "$160.686m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-21"] },
      { period: "2019", value: "$142.980m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-19"] },
      { period: "2018", value: "$115.835m", scope: "HETLIOZ franchise net product sales; U.S. split not disclosed", sourceIds: ["vd-19"] },
      { period: "2017", value: "$89.978m", scope: "HETLIOZ franchise net product sales", sourceIds: ["vd-17", "vd-19"] },
      { period: "2016", value: "$71.671m", scope: "HETLIOZ franchise net product sales", sourceIds: ["vd-17"] },
      { period: "2015", value: "$44.3m", scope: "HETLIOZ franchise net product sales", sourceIds: ["vd-15"] },
      { period: "2014", value: "$12.802m", scope: "HETLIOZ franchise net product sales after April launch", sourceIds: ["vd-14"] },
    ],
    notes: ["Vanda reports the HETLIOZ franchise as a whole and does not provide a consistent U.S.-only or indication-level series."],
    sources: [
      { id: "vd-25", label: "Vanda FY2025 results", url: "https://www.sec.gov/Archives/edgar/data/1347178/000162828026007256/vnda8-k2112026exhibit991.htm" },
      { id: "vd-24", label: "Vanda 2024 annual report", url: "https://www.sec.gov/Archives/edgar/data/1347178/000162828025019996/vnda1231202410k-ars.pdf" },
      { id: "vd-22", label: "Vanda 2022 annual report", url: "https://www.sec.gov/Archives/edgar/data/0001347178/000162828023012597/vnda1231202210k-ars.pdf" },
      { id: "vd-21", label: "Vanda FY2021 results", url: "https://www.sec.gov/Archives/edgar/data/1347178/000162828022003504/vnda8-k2232022exhibit991.htm" },
      { id: "vd-19", label: "Vanda 2019 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1347178/000134717820000003/vnda1231201910k.htm" },
      { id: "vd-17", label: "Vanda 2017 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1347178/000119312518046425/d503767d10k.htm" },
      { id: "vd-15", label: "Vanda FY2015 results", url: "https://www.sec.gov/Archives/edgar/data/1347178/000119312516425704/d102010dex992.htm" },
      { id: "vd-14", label: "Vanda 2014 Form 10-K", url: "https://www.sec.gov/Archives/edgar/data/1347178/000119312515091300/d824216d10k.htm" },
    ],
  },
};
