import type { CommercialModel, TeamRole } from "./commercialModels";

type ModelSpec = {
  indication: string;
  confidence: CommercialModel["confidence"];
  primary: TeamRole;
  managers: number;
  msls: number;
  accounts: TeamRole;
  access: number;
  educators?: TeamRole;
  support: TeamRole;
  medical: number;
  operations: TeamRole;
  insideExtra?: TeamRole;
  geographies: string[];
  evidence: string;
  method: string;
  geographyMethod: string;
  note?: string;
  sources: CommercialModel["sources"];
};

function buildModel(spec: ModelSpec): CommercialModel {
  const field = [
    spec.primary,
    { role: "Regional managers", count: spec.managers },
    { role: "MSLs", count: spec.msls },
    spec.accounts,
    { role: "Field access / reimbursement", count: spec.access },
    spec.educators,
  ].filter((role): role is TeamRole => Boolean(role?.count));
  const inside = [
    spec.support,
    { role: "Medical information / safety", count: spec.medical },
    spec.operations,
    spec.insideExtra,
  ].filter((role): role is TeamRole => Boolean(role?.count));

  return {
    indication: spec.indication,
    confidence: spec.confidence,
    field,
    inside,
    geographies: spec.geographies,
    evidence: spec.evidence,
    method: spec.method,
    geographyMethod: spec.geographyMethod,
    note: spec.note,
    sources: spec.sources,
  };
}

const DIABETES_GEOS = ["California", "Texas", "Florida", "New York / New Jersey", "Great Lakes", "Southeast diabetes belt"];
const MIGRAINE_GEOS = ["Northeast corridor", "California", "Texas", "Florida", "Great Lakes", "Atlanta / Carolinas", "Pacific Northwest"];
const MS_GEOS = ["Northeast MS centers", "Great Lakes", "Florida", "Texas", "California", "Pacific Northwest", "Mountain West"];
const IMMUNOLOGY_GEOS = ["Northeast corridor", "California", "Texas", "Florida / Southeast", "Great Lakes", "Pacific Northwest"];
const RARE_ENDOCRINE_GEOS = ["Boston–New York–Philadelphia", "Cleveland–Chicago", "Atlanta–Durham", "Houston–Dallas", "Phoenix–Los Angeles–Stanford", "Seattle"];
const FEDERAL_GEOS = ["Washington, DC / HHS", "BARDA and SNS depots", "CDC / Atlanta", "DoD medical commands", "Designated regional treatment centers"];

const LILLY_SUPPORT = { label: "Lilly support and savings", url: "https://www.lilly.com/hcp/resources/patient-support-savings" };
const NOVO_SUPPORT = { label: "NovoCare support", url: "https://www.novocare.com/" };
const DIABETES_BURDEN = { label: "American Diabetes Association statistics", url: "https://diabetes.org/about-diabetes/statistics/about-diabetes" };

function insulinModel(brand: string, owner: string, primaryCount: number, note: string, source = LILLY_SUPPORT): CommercialModel {
  return buildModel({
    indication: "Diabetes requiring basal, mealtime or premixed insulin",
    confidence: "Directional",
    primary: { role: "Diabetes account representatives", count: primaryCount },
    managers: 9,
    msls: 6,
    accounts: { role: "IDN / payer accounts", count: 8 },
    access: 8,
    educators: { role: "Diabetes educators", count: 8 },
    support: { role: "Access and affordability support", count: 10 },
    medical: 4,
    operations: { role: "Trade, contracting and analytics", count: 10 },
    geographies: DIABETES_GEOS,
    evidence: `${owner} provides national affordability, pharmacy and device support for ${brand}; product-specific U.S. headcount is not disclosed.`,
    method: "Covers high-decile endocrinology groups, integrated diabetes systems and selected high-volume PCPs; payer, trade and affordability work are weighted more heavily than a launch-sales model.",
    geographyMethod: "Weights diabetes prevalence, endocrinologist density, large integrated systems and Medicaid/commercial access complexity.",
    note,
    sources: [source, DIABETES_BURDEN],
  });
}

function migraineModel(brand: string, owner: string, source: CommercialModel["sources"][number]): CommercialModel {
  return buildModel({
    indication: "Migraine prevention; selected products also cover cluster headache",
    confidence: "Medium",
    primary: { role: "Neurology sales representatives", count: 78 },
    managers: 10,
    msls: 8,
    accounts: { role: "Headache-center / IDN accounts", count: 6 },
    access: 7,
    educators: { role: "Injection educators", count: 4 },
    support: { role: "Coverage and copay support", count: 10 },
    medical: 4,
    operations: { role: "Brand, data and specialty-pharmacy ops", count: 9 },
    geographies: MIGRAINE_GEOS,
    evidence: `${owner} operates a national access program for ${brand}; the product competes across headache specialists and community neurology.`,
    method: "One representative per roughly 180 priority neurologists/headache clinicians, with a virtual/access layer for the broader prescriber tail and CGRP formulary management.",
    geographyMethod: "Weights neurologist and headache-center density, commercially insured lives and large metropolitan referral markets.",
    sources: [source, { label: "American Migraine Foundation treatment resources", url: "https://americanmigrainefoundation.org/find-a-doctor/" }],
  });
}

function fertilityModel(brand: string, owner: string, source: CommercialModel["sources"][number]): CommercialModel {
  return buildModel({
    indication: "Ovulation induction and assisted reproductive technology",
    confidence: "Medium",
    primary: { role: "Fertility account managers", count: 28 },
    managers: 4,
    msls: 5,
    accounts: { role: "IVF network accounts", count: 4 },
    access: 3,
    educators: { role: "Device / injection educators", count: 4 },
    support: { role: "Savings and patient coordinators", count: 7 },
    medical: 2,
    operations: { role: "Trade, inventory and analytics", count: 6 },
    geographies: ["New York / New Jersey", "Boston / Connecticut", "California", "Texas", "Florida", "Chicago", "Washington, DC / Baltimore"],
    evidence: `${owner} provides patient savings, injection materials and clinic support for ${brand}; the customer universe is concentrated in fertility centers.`,
    method: "Territories are sized around IVF clinic networks and cycle volume rather than population; account coverage includes nursing, pharmacy and procurement stakeholders.",
    geographyMethod: "Prioritizes states and metros with the greatest fertility-clinic density and assisted-reproduction cycle volume.",
    sources: [source, { label: "SART clinic directory", url: "https://www.sart.org/clinic-pages/find-a-clinic/" }],
  });
}

function growthModel(brand: string, owner: string, source: CommercialModel["sources"][number], rare = false): CommercialModel {
  return buildModel({
    indication: rare ? "Severe primary IGF-1 deficiency" : "Pediatric and adult growth-hormone disorders",
    confidence: "Medium",
    primary: { role: "Pediatric endocrine account managers", count: rare ? 16 : 38 },
    managers: rare ? 3 : 5,
    msls: rare ? 5 : 6,
    accounts: { role: "Growth-center accounts", count: rare ? 3 : 5 },
    access: rare ? 4 : 6,
    educators: { role: "Device / injection educators", count: rare ? 3 : 7 },
    support: { role: "Care coordinators / nurses", count: rare ? 7 : 11 },
    medical: 2,
    operations: { role: "Specialty-pharmacy and brand ops", count: rare ? 5 : 8 },
    geographies: RARE_ENDOCRINE_GEOS,
    evidence: `${owner} offers access coordination and injection/device support for ${brand}; pediatric endocrinology is the core call point.`,
    method: rare
      ? "Centers on pediatric growth experts and a small community-endocrine layer, with high case-management intensity per patient."
      : "Covers pediatric endocrine centers plus high-volume community practices; nurse/device support and annual reauthorization drive staffing.",
    geographyMethod: "Anchors territories to major children's hospitals, pediatric endocrine programs and dense referral markets.",
    sources: [source, { label: "Pediatric Endocrine Society directory", url: "https://pedsendo.org/patient-resource/find-a-pediatric-endocrinologist/" }],
  });
}

export const SPECIALTY_CANDIDATE_MODELS: Record<string, CommercialModel> = {
  "Humalog Mix 50/50": insulinModel("Humalog Mix 50/50", "Lilly", 62, "Mature premix insulin: emphasize contracting, affordability and continuity of supply over demand generation."),
  "Humalog Mix 75/25": insulinModel("Humalog Mix 75/25", "Lilly", 62, "Mature premix insulin: emphasize contracting, affordability and continuity of supply over demand generation."),
  "Novolog Mix 70/30": insulinModel("NovoLog Mix 70/30", "Novo Nordisk", 66, "Mature premix insulin with broad retail distribution; field effort is concentrated on high-volume diabetes accounts.", { label: "NovoLog Mix savings and support", url: "https://www.novocare.com/diabetes/products/novologmix70-30.html" }),
  "SIGNIFOR LAR KIT": buildModel({
    indication: "Acromegaly after inadequate response to surgery or when surgery is not an option",
    confidence: "High",
    primary: { role: "Rare-endocrine account managers", count: 14 },
    managers: 3,
    msls: 5,
    accounts: { role: "Pituitary-center accounts", count: 3 },
    access: 4,
    educators: { role: "Patient liaison / injection educators", count: 4 },
    support: { role: "Case managers and nurse educators", count: 8 },
    medical: 2,
    operations: { role: "Specialty-pharmacy and brand ops", count: 5 },
    geographies: RARE_ENDOCRINE_GEOS,
    evidence: "Recordati discloses reimbursement, pharmacy, clinical-nurse, patient-liaison and mobile-injection services through R.A.R.E. Patient Support.",
    method: "One account manager covers one to two pituitary-center clusters plus community endocrine spillover; nurse and access ratios reflect monthly intramuscular administration.",
    geographyMethod: "Follows pituitary centers of excellence and high-volume neuroendocrine referral hubs.",
    sources: [
      { label: "SIGNIFOR LAR support model", url: "https://signiforlar.com/hcp/acromegaly/resources-support/" },
      { label: "Pituitary centers of excellence", url: "https://pituitary.org/medical-resources/pituitary-centers-of-excellence/" },
    ],
  }),
  Actimmune: buildModel({
    indication: "Chronic granulomatous disease and severe malignant osteopetrosis",
    confidence: "Medium",
    primary: { role: "Rare-disease account managers", count: 12 },
    managers: 2,
    msls: 5,
    accounts: { role: "Immunology-center accounts", count: 3 },
    access: 4,
    educators: { role: "Clinical educators", count: 4 },
    support: { role: "Case managers / patient support", count: 7 },
    medical: 2,
    operations: { role: "Specialty-pharmacy and brand ops", count: 4 },
    geographies: ["Northeast children's hospitals", "Mid-Atlantic", "Great Lakes", "Texas", "California", "Atlanta / Florida"],
    evidence: "Amgen By Your Side provides rare-disease enrollment, access and patient support; prescribers cluster in immunology and transplant-capable children's hospitals.",
    method: "National rare-disease coverage with account managers assigned to center clusters; high MSL and case-management ratios support diagnosis and long-term adherence.",
    geographyMethod: "Prioritizes major pediatric immunology, infectious-disease and bone-marrow-transplant centers.",
    sources: [
      { label: "ACTIMMUNE HCP resources", url: "https://www.actimmunehcp.com/" },
      { label: "Primary Immunodeficiency treatment centers", url: "https://primaryimmune.org/resources/find-a-center" },
    ],
  }),
  Activase: buildModel({
    indication: "Acute ischemic stroke, acute myocardial infarction and massive pulmonary embolism",
    confidence: "Medium",
    primary: { role: "Hospital acute-care representatives", count: 48 },
    managers: 7,
    msls: 9,
    accounts: { role: "Stroke-system / IDN accounts", count: 7 },
    access: 3,
    educators: { role: "Protocol educators", count: 5 },
    support: { role: "Medical response / order support", count: 5 },
    medical: 5,
    operations: { role: "Hospital contracting and distribution", count: 8 },
    geographies: ["Northeast stroke corridor", "Great Lakes", "Southeast", "Texas", "California", "Mountain West / Pacific Northwest"],
    evidence: "Genentech maintains hospital resources, MSL access and a stroke urgency toolkit; use is protocol-driven inside certified acute-care systems.",
    method: "Territories cover comprehensive and primary stroke centers plus top emergency systems; medical/protocol roles carry more weight than consumer demand generation.",
    geographyMethod: "Follows certified stroke-center density, large emergency departments and regional referral networks.",
    sources: [
      { label: "Genentech Activase resources", url: "https://www.gene.com/medical-professionals/medicines" },
      { label: "Joint Commission stroke centers", url: "https://www.qualitycheck.org/" },
    ],
  }),
  Adakveo: buildModel({
    indication: "Reduction of vaso-occlusive crises in sickle cell disease",
    confidence: "Medium",
    primary: { role: "Sickle-cell account managers", count: 30 },
    managers: 5,
    msls: 8,
    accounts: { role: "Center / IDN accounts", count: 6 },
    access: 6,
    educators: { role: "Clinical educators", count: 4 },
    support: { role: "Case managers / infusion support", count: 9 },
    medical: 3,
    operations: { role: "Distribution, brand and analytics", count: 6 },
    geographies: ["Southeast sickle-cell belt", "New York / New Jersey", "Mid-Atlantic", "Texas", "California", "Chicago / Detroit"],
    evidence: "Novartis lists active U.S. patient assistance for this monthly infusion product; treatment is centered in hematology and sickle-cell programs.",
    method: "One account manager covers approximately 20–30 priority centers plus community hematology; field access and infusion support reflect medical-benefit reimbursement.",
    geographyMethod: "Weights sickle-cell prevalence and comprehensive treatment-center density, led by the Southeast and major urban systems.",
    sources: [
      { label: "Novartis U.S. product portfolio", url: "https://www.novartis.com/us-en/about/products" },
      { label: "Sickle Cell Disease Association affiliates", url: "https://www.sicklecelldisease.org/about-us/member-organizations/" },
    ],
  }),
  Admelog: insulinModel("Admelog", "Sanofi", 64, "Rapid-acting insulin with national access and contracting needs; specialist promotion is focused on high-volume endocrinology.", { label: "Sanofi patient connection", url: "https://www.sanofipatientconnection.com/" }),
  Aimovig: migraineModel("Aimovig", "Amgen", { label: "Aimovig coverage and support", url: "https://www.aimovighcp.com/resources/support" }),
  Ajovy: migraineModel("Ajovy", "Teva", { label: "AJOVY HCP site", url: "https://www.ajovyhcp.com/" }),
  Anthim: buildModel({
    indication: "Treatment or prophylaxis of inhalational anthrax",
    confidence: "High",
    primary: { role: "Federal preparedness accounts", count: 5 },
    managers: 1,
    msls: 4,
    accounts: { role: "Government contracting / SNS", count: 4 },
    access: 0,
    educators: { role: "Emergency-response educators", count: 3 },
    support: { role: "Order and deployment coordination", count: 4 },
    medical: 3,
    operations: { role: "Stockpile, quality and logistics", count: 6 },
    geographies: FEDERAL_GEOS,
    evidence: "Elusys states that ANTHIM is supplied to the U.S. government for public-health preparedness and has BARDA, DoD and NIH funding history.",
    method: "No conventional sales force: a compact federal-account, medical and supply-readiness team supports procurement, stockpile rotation and emergency deployment.",
    geographyMethod: "Targets federal decision makers, stockpile infrastructure and designated emergency-response centers rather than population-based territories.",
    sources: [
      { label: "ANTHIM government-supply model", url: "https://anthim.com/" },
      { label: "Strategic National Stockpile overview", url: "https://www.aspr.gov/readiness-response/medical-countermeasures-biodefense/sns/stockpile-products" },
    ],
  }),
  Apidra: insulinModel("Apidra", "Sanofi", 64, "Rapid-acting insulin; prioritize payer access, high-volume endocrinology and retail continuity.", { label: "Sanofi patient connection", url: "https://www.sanofipatientconnection.com/" }),
  Aranesp: buildModel({
    indication: "Anemia due to chronic kidney disease or myelosuppressive chemotherapy",
    confidence: "Medium",
    primary: { role: "Renal / oncology account representatives", count: 48 },
    managers: 7,
    msls: 8,
    accounts: { role: "Dialysis / health-system accounts", count: 8 },
    access: 7,
    educators: { role: "Protocol educators", count: 4 },
    support: { role: "Benefits and patient support", count: 7 },
    medical: 4,
    operations: { role: "Contracting, distribution and analytics", count: 8 },
    geographies: ["Southeast CKD belt", "Texas", "Northeast corridor", "Great Lakes", "California", "Mid-Atlantic"],
    evidence: "Amgen maintains a dedicated nephrology portfolio, orderable office resources and SupportPlus access services for ARANESP.",
    method: "Covers large nephrology groups, dialysis organizations and oncology systems; account and contracting capacity is elevated because administration and reimbursement sit inside institutions.",
    geographyMethod: "Weights CKD burden, dialysis-center density and large oncology/renal integrated systems.",
    sources: [
      { label: "Amgen nephrology portfolio", url: "https://www.amgennephrology.com/products" },
      { label: "Amgen SupportPlus", url: "https://www.amgensupportplus.com/patient" },
    ],
  }),
  Arcalyst: buildModel({
    indication: "Recurrent pericarditis and selected IL-1–mediated rare disorders",
    confidence: "Medium",
    primary: { role: "Cardiology account managers", count: 30 },
    managers: 4,
    msls: 7,
    accounts: { role: "Pericarditis-center accounts", count: 5 },
    access: 6,
    educators: { role: "Injection educators", count: 4 },
    support: { role: "Kiniksa OneConnect case managers", count: 8 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 6 },
    geographies: ["Boston–New York–Philadelphia", "Cleveland–Chicago", "Baltimore–DC", "Atlanta–Florida", "Texas", "California"],
    evidence: "Kiniksa markets ARCALYST through a specialist clinical-sales model and centralized OneConnect support for a concentrated recurrent-pericarditis market.",
    method: "Territories center on referral cardiologists and academic pericardial-disease programs; access and onboarding remain high because of biologic prior authorization and self-injection.",
    geographyMethod: "Anchors to tertiary cardiology systems and high-density cardiology metros, with national virtual coverage for the long tail.",
    sources: [
      { label: "ARCALYST HCP resources", url: "https://www.arcalysthcp.com/" },
      { label: "ARCALYST recurrent-pericarditis overview", url: "https://www.arcalyst.com/recurrent-pericarditis" },
    ],
  }),
  Avonex: buildModel({
    indication: "Relapsing forms of multiple sclerosis",
    confidence: "High",
    primary: { role: "MS sales representatives", count: 48 },
    managers: 7,
    msls: 10,
    accounts: { role: "MS-center / IDN accounts", count: 6 },
    access: 6,
    educators: { role: "MS nurse educators", count: 9 },
    support: { role: "Benefits coordinators / nurses", count: 11 },
    medical: 4,
    operations: { role: "Specialty-pharmacy and brand ops", count: 8 },
    geographies: MS_GEOS,
    evidence: "Biogen Support Services explicitly provides benefits support and MS-certified nurse educators for in-home or virtual injection training.",
    method: "Covers MS centers and high-volume community neurologists, with a smaller mature-brand sales footprint and a durable nurse/access layer.",
    geographyMethod: "Weights MS-center density, neurologist concentration and large insured populations.",
    sources: [
      { label: "Biogen Support Services for AVONEX", url: "https://hcp.avonex.com/en_us/home/hcp-start-avonex/hcp-support-program.html" },
      { label: "Consortium of MS Centers", url: "https://www.mscare.org/page/clinic_directory" },
    ],
  }),
  Basaglar: insulinModel("Basaglar", "Lilly", 68, "Basal insulin with broad PCP reach; a standalone owner would use targeted field coverage plus strong payer and pharmacy operations."),
  Benlysta: buildModel({
    indication: "Systemic lupus erythematosus and lupus nephritis",
    confidence: "Medium",
    primary: { role: "Rheumatology sales representatives", count: 78 },
    managers: 10,
    msls: 12,
    accounts: { role: "Lupus-center / IDN accounts", count: 8 },
    access: 9,
    educators: { role: "Nurse educators", count: 7 },
    support: { role: "Gateway access coordinators", count: 12 },
    medical: 5,
    operations: { role: "Infusion, specialty-pharmacy and brand ops", count: 11 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "Together with BENLYSTA and BENLYSTA Gateway support benefits, prior authorization, infusion-site selection, reimbursement and nurse education across IV and self-injected forms.",
    method: "Broad rheumatology coverage with nephrology overlays; extra accounts, access and operations support dual medical/pharmacy benefit pathways.",
    geographyMethod: "Weights rheumatologist density, lupus-center concentration, diverse high-prevalence metros and large infusion networks.",
    sources: [
      { label: "BENLYSTA access and start support", url: "https://www.benlystahcp.com/access/starting-a-patient/" },
      { label: "Lupus clinical-trial and care network", url: "https://www.lupus.org/resources/find-a-support-group" },
    ],
  }),
  Betaseron: buildModel({
    indication: "Relapsing forms of multiple sclerosis",
    confidence: "High",
    primary: { role: "MS sales representatives", count: 38 },
    managers: 6,
    msls: 8,
    accounts: { role: "MS-center accounts", count: 5 },
    access: 5,
    educators: { role: "BETA nurse educators", count: 8 },
    support: { role: "Coverage specialists / nurses", count: 10 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 7 },
    geographies: MS_GEOS,
    evidence: "BETAPLUS provides 24/7 MS-trained nurse support, coverage specialists, injection-device education and financial assistance.",
    method: "A mature-brand field footprint covers MS centers and selected community neurology; nurse and access support are retained for injection persistence.",
    geographyMethod: "Weights MS-center density and neurologist concentration, with virtual coverage across lower-density states.",
    sources: [
      { label: "BETASERON support", url: "https://www.betaseron.com/" },
      { label: "Consortium of MS Centers", url: "https://www.mscare.org/page/clinic_directory" },
    ],
  }),
  "BYNFEZIA PEN": buildModel({
    indication: "Acromegaly, carcinoid tumors and VIPomas requiring octreotide",
    confidence: "Directional",
    primary: { role: "Rare-endocrine / NET account managers", count: 14 },
    managers: 3,
    msls: 5,
    accounts: { role: "Pituitary / NET center accounts", count: 3 },
    access: 4,
    educators: { role: "Pen trainers", count: 4 },
    support: { role: "Patient access coordinators", count: 6 },
    medical: 2,
    operations: { role: "Specialty-pharmacy and brand ops", count: 4 },
    geographies: RARE_ENDOCRINE_GEOS,
    evidence: "Public materials emphasize sterile self-injection training for the multidose pen; no U.S. product-specific organization is disclosed.",
    method: "A small shared rare-endocrine team covers pituitary and neuroendocrine centers; device training and specialty-pharmacy access account for most incremental support.",
    geographyMethod: "Follows pituitary centers, neuroendocrine tumor programs and high-volume academic endocrinology hubs.",
    sources: [
      { label: "BYNFEZIA PEN labeling and training", url: "https://bynfeziapen.com/" },
      { label: "Pituitary centers of excellence", url: "https://pituitary.org/medical-resources/pituitary-centers-of-excellence/" },
    ],
  }),
  Cablivi: buildModel({
    indication: "Acquired thrombotic thrombocytopenic purpura",
    confidence: "High",
    primary: { role: "Rare-hematology account managers", count: 18 },
    managers: 3,
    msls: 7,
    accounts: { role: "TTP-center / hospital accounts", count: 5 },
    access: 5,
    educators: { role: "Transition-of-care educators", count: 5 },
    support: { role: "CABLIVI case managers", count: 9 },
    medical: 3,
    operations: { role: "Hospital-to-home and specialty-pharmacy ops", count: 6 },
    geographies: ["Northeast academic hospitals", "Mid-Atlantic", "Great Lakes", "Southeast", "Texas", "California"],
    evidence: "CABLIVI Patient Solutions discloses dedicated case managers and hospital-to-home specialty-pharmacy coordination.",
    method: "Accounts are sized around tertiary hematology hospitals; MSL, transition-of-care and case-management coverage is high relative to sales because starts are acute and uncommon.",
    geographyMethod: "Prioritizes high-volume academic hematology centers and regional referral hospitals rather than population alone.",
    sources: [
      { label: "CABLIVI Patient Solutions", url: "https://hcp.cablivi.com/starting-and-staying-on-cablivi/cablivi-patient-solutions" },
      { label: "Sanofi HemAssist", url: "https://www.sanofihemassist.com/us/our-products/cablivi" },
    ],
  }),
  Campath: buildModel({
    indication: "B-cell chronic lymphocytic leukemia through restricted distribution",
    confidence: "High",
    primary: { role: "Restricted-program accounts", count: 5 },
    managers: 1,
    msls: 3,
    accounts: { role: "National oncology accounts", count: 2 },
    access: 1,
    educators: { role: "Program educators", count: 2 },
    support: { role: "Distribution coordinators", count: 4 },
    medical: 3,
    operations: { role: "Safety and restricted-distribution ops", count: 4 },
    geographies: ["National cancer centers", "Northeast", "Mid-Atlantic", "Great Lakes", "Texas", "California"],
    evidence: "NCI states that CAMPATH is available only through the U.S. Campath Distribution Program, which ships directly to registered doctors, hospitals or pharmacies.",
    method: "No conventional promotion: the model supports restricted access, safety, medical requests and a small number of expert oncology centers.",
    geographyMethod: "Targets major CLL referral centers nationally; central program operations cover all other geographies.",
    sources: [
      { label: "NCI CAMPATH distribution description", url: "https://www.cancer.gov/about-cancer/treatment/drugs/alemtuzumab" },
      { label: "NCI cancer-center directory", url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find" },
    ],
  }),
  "Cathflo Activase": buildModel({
    indication: "Restoration of function to occluded central venous access devices",
    confidence: "Medium",
    primary: { role: "Hospital account representatives", count: 36 },
    managers: 5,
    msls: 5,
    accounts: { role: "IDN / infusion-network accounts", count: 7 },
    access: 2,
    educators: { role: "Nursing / protocol educators", count: 6 },
    support: { role: "Order and medical-response support", count: 4 },
    medical: 3,
    operations: { role: "Hospital contracting and distribution", count: 7 },
    geographies: ["Northeast health systems", "Great Lakes", "Southeast", "Texas", "California", "Pacific Northwest"],
    evidence: "Genentech provides hospital-facing product, medical-information, MSL and patient-resource support for CATHFLO ACTIVASE.",
    method: "Shared acute-care representatives cover large IDNs, infusion centers and hospital pharmacy; nurse educators support line-clearance protocols.",
    geographyMethod: "Weights hospital beds, oncology infusion capacity and large integrated delivery networks.",
    sources: [
      { label: "Genentech CATHFLO resources", url: "https://www.gene.com/medical-professionals/medicines/cathflo-activase" },
    ],
  }),
  Cimzia: buildModel({
    indication: "Rheumatology, gastroenterology and dermatology inflammatory diseases",
    confidence: "High",
    primary: { role: "Immunology sales representatives", count: 96 },
    managers: 12,
    msls: 14,
    accounts: { role: "Infusion / large-group accounts", count: 10 },
    access: 12,
    educators: { role: "Nurse navigators / injection educators", count: 8 },
    support: { role: "CIMplicity access coordinators", count: 14 },
    medical: 6,
    operations: { role: "Buy-and-bill, trade and brand ops", count: 12 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "CIMplicity discloses nurse navigators, field reimbursement managers, buy-and-bill resources and separate rheumatology, GI and dermatology workflows.",
    method: "Three-specialty coverage with dedicated large-practice accounts; heavier reimbursement and operations staffing supports in-office injection and specialty-pharmacy pathways.",
    geographyMethod: "Weights rheumatology, GI and dermatology density plus in-office injection sites and large multispecialty groups.",
    sources: [
      { label: "CIMZIA in-office resources", url: "https://www.cimziainoffice.com/resources" },
      { label: "CIMplicity nurse support", url: "https://www.cimzia.com/in-office-injections" },
    ],
  }),
  Cinqair: buildModel({
    indication: "Severe eosinophilic asthma",
    confidence: "Medium",
    primary: { role: "Severe-asthma sales representatives", count: 42 },
    managers: 6,
    msls: 7,
    accounts: { role: "Allergy / pulmonary accounts", count: 6 },
    access: 6,
    educators: { role: "Infusion educators", count: 4 },
    support: { role: "Teva Support Solutions coordinators", count: 7 },
    medical: 3,
    operations: { role: "Infusion, contracting and brand ops", count: 7 },
    geographies: ["Northeast", "Florida / Southeast", "Texas", "California", "Great Lakes", "Ohio Valley / Appalachia"],
    evidence: "Teva Support Solutions covers medication and administration costs, while CINQAIR can be delivered through HCP-supervised infusion.",
    method: "Targets severe-asthma allergists, pulmonologists and infusion-capable practices; medical-benefit access and site-of-care support are weighted above consumer reach.",
    geographyMethod: "Weights severe-asthma burden, allergy/pulmonary specialist density and infusion networks.",
    sources: [
      { label: "CINQAIR support", url: "https://www.hcp.cinqairpp.tevapharm.com/support/" },
      { label: "AAAAI allergist directory", url: "https://allergist.aaaai.org/find/" },
    ],
  }),
  Cosentyx: buildModel({
    indication: "Multiple dermatology and rheumatology inflammatory diseases",
    confidence: "Medium",
    primary: { role: "Immunology sales representatives", count: 142 },
    managers: 17,
    msls: 18,
    accounts: { role: "Large-group / IDN accounts", count: 12 },
    access: 14,
    educators: { role: "Injection educators", count: 8 },
    support: { role: "COSENTYX Connect coordinators", count: 18 },
    medical: 7,
    operations: { role: "Specialty-pharmacy, contracting and brand ops", count: 16 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "COSENTYX Connect provides national insurance, financial and ongoing support across a broad dermatology/rheumatology label.",
    method: "Parallel high-decile dermatology and rheumatology territories with shared accounts, MSLs and access; sized for a multi-indication blockbuster, not a narrow orphan launch.",
    geographyMethod: "Weights dermatologist/rheumatologist density, large specialty groups and commercially insured populations.",
    sources: [
      { label: "COSENTYX Connect", url: "https://support.cosentyx.com/" },
      { label: "Novartis patient support", url: "https://www.novartis.com/us-en/patients-and-caregivers/patient-assistance/novartis-patient-support" },
    ],
  }),
  Crysvita: buildModel({
    indication: "X-linked hypophosphatemia and tumor-induced osteomalacia",
    confidence: "High",
    primary: { role: "Rare-metabolic account managers", count: 24 },
    managers: 4,
    msls: 8,
    accounts: { role: "Metabolic-bone center accounts", count: 5 },
    access: 7,
    educators: { role: "Clinical educators", count: 8 },
    support: { role: "Kyowa Kirin case managers", count: 11 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 7 },
    geographies: RARE_ENDOCRINE_GEOS,
    evidence: "Kyowa Kirin Cares explicitly provides case managers, clinical educators, benefits investigation and ongoing treatment support.",
    method: "Territories cover metabolic-bone and pediatric endocrine center clusters; high educator and case-manager ratios support diagnosis, access and chronic injection adherence.",
    geographyMethod: "Anchors to academic metabolic-bone, nephrology and pediatric endocrine referral programs.",
    sources: [
      { label: "CRYSVITA HCP support", url: "https://www.kyowakirincares.com/crysvita-healthcare-providers/" },
      { label: "CRYSVITA product site", url: "https://www.crysvita.com/" },
    ],
  }),
  Digifab: buildModel({
    indication: "Life-threatening or potentially life-threatening digoxin toxicity",
    confidence: "Medium",
    primary: { role: "Hospital / toxicology representatives", count: 16 },
    managers: 3,
    msls: 4,
    accounts: { role: "Poison-center / IDN accounts", count: 4 },
    access: 0,
    educators: { role: "Emergency-care educators", count: 3 },
    support: { role: "24-hour medical / order support", count: 4 },
    medical: 3,
    operations: { role: "Emergency inventory and distribution", count: 4 },
    geographies: ["National poison-center network", "Northeast hospital systems", "Southeast", "Texas", "California", "Great Lakes"],
    evidence: "DIGIFab maintains a 24-hour medical-information line; use depends on emergency inventory and toxicology protocols rather than routine prescribing.",
    method: "A small hospital team covers major emergency systems and poison centers; central inventory readiness and medical response replace a broad sales footprint.",
    geographyMethod: "Targets regional poison centers, high-volume emergency departments and large health systems.",
    sources: [
      { label: "DIGIFab medical resources", url: "https://digifab.health/en-us/digifab-resources/faqs.html" },
      { label: "America's Poison Centers", url: "https://poisoncenters.org/find-your-local-poison-center" },
    ],
  }),
  Dupixent: buildModel({
    indication: "Multiple type-2 inflammatory diseases across dermatology, respiratory and GI specialties",
    confidence: "High",
    primary: { role: "Specialty sales representatives", count: 170 },
    managers: 20,
    msls: 22,
    accounts: { role: "Large-group / IDN accounts", count: 14 },
    access: 18,
    educators: { role: "Nurse educators", count: 14 },
    support: { role: "MyWay case managers", count: 28 },
    medical: 8,
    operations: { role: "Specialty-pharmacy, contracting and brand ops", count: 24 },
    insideExtra: { role: "Virtual sales / long-tail coverage", count: 12 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "DUPIXENT MyWay explicitly combines sales professionals, field reimbursement managers, case managers and nurse educators across multiple specialties.",
    method: "Dedicated specialty pods cover dermatology, allergy/pulmonology and GI, sharing national accounts, access and patient services; scale reflects a broad multi-indication market.",
    geographyMethod: "Weights specialist density, large group practices, insured population and high type-2 inflammatory disease burden.",
    sources: [
      { label: "DUPIXENT MyWay team", url: "https://www.dupixenthcp.com/patient-support/dupixent-myway" },
      { label: "DUPIXENT coverage support", url: "https://www.dupixenthcp.com/patient-support/coverage-support" },
    ],
  }),
  Ebanga: buildModel({
    indication: "Treatment of Zaire ebolavirus infection",
    confidence: "Directional",
    primary: { role: "Federal / global-health accounts", count: 4 },
    managers: 1,
    msls: 4,
    accounts: { role: "Government contracting / stockpile", count: 4 },
    access: 0,
    educators: { role: "Outbreak-response educators", count: 3 },
    support: { role: "Deployment coordination", count: 4 },
    medical: 3,
    operations: { role: "Stockpile, quality and logistics", count: 5 },
    geographies: FEDERAL_GEOS,
    evidence: "EBANGA is a public-health countermeasure associated with government/WHO stockpile planning, not a recurring office-prescriber market.",
    method: "No conventional commercial field force: a compact government-account, medical and logistics organization supports procurement and emergency deployment.",
    geographyMethod: "Focuses on federal preparedness agencies, designated biocontainment centers and stockpile logistics nodes.",
    sources: [
      { label: "Strategic National Stockpile", url: "https://www.aspr.gov/readiness-response/medical-countermeasures-biodefense/sns/stockpile-products" },
      { label: "WHO Ebola therapeutics stockpile discussion", url: "https://iris.who.int/bitstream/handle/10665/376336/9789240069114-eng.pdf?sequence=1" },
    ],
  }),
  "Egrifta SV": buildModel({
    indication: "Reduction of excess abdominal fat in adults with HIV and lipodystrophy",
    confidence: "High",
    primary: { role: "HIV specialty representatives", count: 24 },
    managers: 4,
    msls: 6,
    accounts: { role: "HIV-center / IDN accounts", count: 4 },
    access: 5,
    educators: { role: "Field reimbursement managers", count: 5 },
    support: { role: "Patient care coordinators / nurse navigators", count: 10 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 6 },
    geographies: ["New York / New Jersey", "California", "Florida", "Texas", "Atlanta", "Chicago", "Washington, DC"],
    evidence: "THERA Patient Support discloses patient care coordinators, field reimbursement managers and nurse navigators for access and injection training.",
    method: "Territories cover high-volume HIV clinics and urban ID programs; inside support is high because every start flows through centralized reimbursement and specialty pharmacy.",
    geographyMethod: "Weights HIV prevalence, Ryan White clinic density and large metropolitan infectious-disease practices.",
    sources: [
      { label: "EGRIFTA SV THERA support team", url: "https://hcp.egriftasv.com/support/" },
      { label: "HRSA Ryan White clinic locator", url: "https://findhivcare.hrsa.gov/" },
    ],
  }),
  "Egrifta WR": buildModel({
    indication: "Reduction of excess abdominal fat in adults with HIV and lipodystrophy",
    confidence: "High",
    primary: { role: "HIV specialty representatives", count: 24 },
    managers: 4,
    msls: 6,
    accounts: { role: "HIV-center / IDN accounts", count: 4 },
    access: 5,
    educators: { role: "Field reimbursement managers", count: 5 },
    support: { role: "Patient care coordinators / nurse navigators", count: 10 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 6 },
    geographies: ["New York / New Jersey", "California", "Florida", "Texas", "Atlanta", "Chicago", "Washington, DC"],
    evidence: "THERA Patient Support discloses patient care coordinators, field reimbursement managers and nurse navigators for tesamorelin access and injection training.",
    method: "Uses the same HIV-specialty platform as EGRIFTA SV; a standalone model would not duplicate teams by formulation.",
    geographyMethod: "Weights HIV prevalence, Ryan White clinic density and large metropolitan infectious-disease practices.",
    note: "Portfolio view: combine SV and WR resources if both formulations transfer; do not add the two headcounts together.",
    sources: [
      { label: "THERA patient support", url: "https://hcp.egriftasv.com/support/" },
      { label: "HRSA Ryan White clinic locator", url: "https://findhivcare.hrsa.gov/" },
    ],
  }),
  Emgality: migraineModel("Emgality", "Lilly", { label: "Emgality access support", url: "https://emgality.lilly.com/hcp/savings-support" }),
  Enbrel: buildModel({
    indication: "Multiple rheumatology and dermatology inflammatory diseases",
    confidence: "High",
    primary: { role: "Immunology sales representatives", count: 108 },
    managers: 14,
    msls: 14,
    accounts: { role: "Large-group / IDN accounts", count: 10 },
    access: 12,
    educators: { role: "Nurse partners", count: 8 },
    support: { role: "SupportPlus access coordinators", count: 15 },
    medical: 5,
    operations: { role: "Specialty-pharmacy, contracting and brand ops", count: 13 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "Amgen SupportPlus offers reimbursement assistance, coverage verification and nurse-partner services for ENBREL.",
    method: "Mature broad-label coverage across high-volume rheumatology and dermatology, with national accounts and access maintained against biosimilar and formulary pressure.",
    geographyMethod: "Weights rheumatologist/dermatologist density, large groups and commercially insured populations.",
    sources: [
      { label: "ENBREL support", url: "https://www.enbrel.com/support" },
      { label: "Amgen SupportPlus", url: "https://www.amgensupportplus.com/" },
    ],
  }),
  "Enbrel Mini": buildModel({
    indication: "Multiple rheumatology and dermatology inflammatory diseases",
    confidence: "High",
    primary: { role: "Immunology sales representatives", count: 108 },
    managers: 14,
    msls: 14,
    accounts: { role: "Large-group / IDN accounts", count: 10 },
    access: 12,
    educators: { role: "Nurse partners / device trainers", count: 10 },
    support: { role: "SupportPlus access coordinators", count: 15 },
    medical: 5,
    operations: { role: "Specialty-pharmacy, contracting and device ops", count: 14 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "ENBREL Mini uses the established ENBREL commercial and SupportPlus platform, adding device education rather than a separate field force.",
    method: "Uses the ENBREL portfolio team with incremental device training; the count represents the full standalone franchise, not an additive Mini-only team.",
    geographyMethod: "Weights rheumatologist/dermatologist density, large groups and commercially insured populations.",
    note: "Portfolio view: ENBREL and ENBREL Mini share one platform; do not sum their modeled teams.",
    sources: [
      { label: "ENBREL support", url: "https://www.enbrel.com/support" },
      { label: "Amgen SupportPlus", url: "https://www.amgensupportplus.com/" },
    ],
  }),
  Enspryng: buildModel({
    indication: "Neuromyelitis optica spectrum disorder in AQP4-positive adults",
    confidence: "High",
    primary: { role: "Rare-neurology account managers", count: 22 },
    managers: 4,
    msls: 8,
    accounts: { role: "NMOSD-center accounts", count: 4 },
    access: 6,
    educators: { role: "Injection nurse educators", count: 5 },
    support: { role: "Access Solutions coordinators", count: 8 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 6 },
    geographies: ["Northeast neuroimmunology centers", "Mid-Atlantic", "Great Lakes", "Texas", "California", "Southeast", "Pacific Northwest"],
    evidence: "Genentech Access Solutions provides benefits investigation, appeals, copay referrals and optional nurse injection training for ENSPRYNG.",
    method: "One account manager covers neuroimmunology center clusters plus selected community MS practices; MSL and access staffing are high for diagnosis and biologic initiation.",
    geographyMethod: "Anchors to academic neuroimmunology/NMOSD centers and major MS referral markets.",
    sources: [
      { label: "ENSPRYNG Access Solutions", url: "https://www.genentech-access.com/hcp/brands/enspryng.html" },
      { label: "ENSPRYNG start and nurse support", url: "https://www.genentech-pro.com/content/dam/gene/accesssolutions/pdfs/start-form/ENSPRYNG-Start-Form.pdf" },
    ],
  }),
  Entyvio: buildModel({
    indication: "Ulcerative colitis and Crohn's disease",
    confidence: "High",
    primary: { role: "Gastroenterology sales representatives", count: 116 },
    managers: 14,
    msls: 16,
    accounts: { role: "IBD-center / infusion accounts", count: 12 },
    access: 14,
    educators: { role: "Nurse educators", count: 9 },
    support: { role: "EntyvioConnect coordinators", count: 18 },
    medical: 6,
    operations: { role: "Infusion, specialty-pharmacy and brand ops", count: 15 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "EntyvioConnect provides benefits, prior authorization, start/bridge, infusion referral, copay and nurse support for IV and subcutaneous pathways.",
    method: "Broad high-decile GI coverage plus IBD and infusion accounts; access/operations capacity reflects both medical-benefit infusion and pharmacy-benefit self-injection.",
    geographyMethod: "Weights gastroenterologist density, IBD centers, infusion capacity and commercially insured populations.",
    sources: [
      { label: "ENTYVIO HCP patient support", url: "https://www.entyviohcp.com/patient-support" },
      { label: "EntyvioConnect practice resources", url: "https://www.entyviohcp.com/patient-support-resources" },
    ],
  }),
  "Entyvio Pen": buildModel({
    indication: "Ulcerative colitis and Crohn's disease maintenance by self-injection",
    confidence: "High",
    primary: { role: "Gastroenterology sales representatives", count: 116 },
    managers: 14,
    msls: 16,
    accounts: { role: "IBD-center / large-group accounts", count: 12 },
    access: 14,
    educators: { role: "Pen / transition nurse educators", count: 11 },
    support: { role: "EntyvioConnect coordinators", count: 18 },
    medical: 6,
    operations: { role: "Specialty-pharmacy and brand ops", count: 15 },
    geographies: IMMUNOLOGY_GEOS,
    evidence: "EntyvioConnect supports both IV ENTYVIO and the ENTYVIO Pen, including nurse education and pharmacy access.",
    method: "Uses the same GI platform as IV ENTYVIO with incremental pen-transition education; this is a franchise model, not an additive formulation team.",
    geographyMethod: "Weights gastroenterologist density, IBD centers, large groups and commercially insured populations.",
    note: "Portfolio view: ENTYVIO and ENTYVIO Pen share one platform; do not sum their modeled teams.",
    sources: [
      { label: "EntyvioConnect", url: "https://www.entyvio.com/entyvioconnect" },
      { label: "ENTYVIO HCP patient support", url: "https://www.entyviohcp.com/patient-support" },
    ],
  }),
  "Epogen/Procrit": buildModel({
    indication: "Anemia due to chronic kidney disease and selected chemotherapy-related use",
    confidence: "Medium",
    primary: { role: "Renal / hospital account representatives", count: 50 },
    managers: 7,
    msls: 8,
    accounts: { role: "Dialysis / IDN accounts", count: 9 },
    access: 7,
    educators: { role: "Protocol educators", count: 4 },
    support: { role: "Benefits and patient support", count: 7 },
    medical: 4,
    operations: { role: "Contracting, distribution and analytics", count: 9 },
    geographies: ["Southeast CKD belt", "Texas", "Northeast corridor", "Great Lakes", "California", "Mid-Atlantic"],
    evidence: "Amgen maintains dedicated EPOGEN nephrology materials and SupportPlus resources; the core customers are dialysis organizations and renal systems.",
    method: "National renal account model with targeted nephrology representatives; contracting and distribution carry more weight than brand promotion in a mature ESA category.",
    geographyMethod: "Weights CKD burden, dialysis-center density and national/regional renal organizations.",
    sources: [
      { label: "EPOGEN HCP support", url: "https://www.amgensupportplus.com/hcp/epogen" },
      { label: "Amgen nephrology resources", url: "https://www.amgennephrology.com/products" },
    ],
  }),
  Evenity: buildModel({
    indication: "Osteoporosis in postmenopausal women at high risk for fracture",
    confidence: "High",
    primary: { role: "Bone-health sales representatives", count: 86 },
    managers: 11,
    msls: 10,
    accounts: { role: "Bone-health / IDN accounts", count: 8 },
    access: 10,
    educators: { role: "Office administration educators", count: 7 },
    support: { role: "SupportPlus benefits coordinators", count: 12 },
    medical: 4,
    operations: { role: "Buy-and-bill, contracting and brand ops", count: 10 },
    geographies: ["Northeast corridor", "Florida", "California", "Texas", "Great Lakes", "Arizona / Mountain West", "Southeast"],
    evidence: "Amgen discloses Field Reimbursement Managers, medical-benefit verification and office fulfillment support for EVENITY.",
    method: "Targets osteoporosis-focused endocrinology, rheumatology and high-volume bone-health practices; buy-and-bill access drives office and reimbursement coverage.",
    geographyMethod: "Weights older female population, osteoporosis specialist density and office-administered biologic capacity.",
    sources: [
      { label: "EVENITY access and support", url: "https://www.evenityhcp.com/access-and-support" },
      { label: "Amgen SupportPlus", url: "https://www.amgensupportplus.com/" },
    ],
  }),
  Evkeeza: buildModel({
    indication: "Homozygous familial hypercholesterolemia",
    confidence: "High",
    primary: { role: "Rare-lipid account managers", count: 15 },
    managers: 3,
    msls: 6,
    accounts: { role: "Lipid-center / apheresis accounts", count: 4 },
    access: 5,
    educators: { role: "Infusion educators", count: 4 },
    support: { role: "myRARE patient navigators", count: 8 },
    medical: 3,
    operations: { role: "Infusion and specialty distribution ops", count: 6 },
    geographies: ["Boston–New York–Philadelphia", "Cleveland–Chicago", "Baltimore–DC", "Houston–Dallas", "Los Angeles–San Francisco", "Seattle"],
    evidence: "EVKEEZA materials describe myRARE patient support for access, reimbursement and ongoing coordination in a very small HoFH market.",
    method: "One account manager covers lipid/apheresis center clusters; MSL, access and navigator intensity is high because diagnosis and infusion coordination dominate workload.",
    geographyMethod: "Anchors to major lipid clinics, genetic dyslipidemia experts and LDL-apheresis centers.",
    sources: [
      { label: "EVKEEZA HCP resources", url: "https://www.evkeezahcp.com/" },
      { label: "Family Heart Foundation care resources", url: "https://familyheart.org/find-specialist" },
    ],
  }),
  Fasenra: buildModel({
    indication: "Severe eosinophilic asthma and eosinophilic granulomatosis with polyangiitis",
    confidence: "High",
    primary: { role: "Respiratory biologic representatives", count: 104 },
    managers: 13,
    msls: 14,
    accounts: { role: "Severe-asthma / IDN accounts", count: 9 },
    access: 11,
    educators: { role: "Nurse / injection educators", count: 8 },
    support: { role: "FASENRA 360 / Access 360 coordinators", count: 14 },
    medical: 5,
    operations: { role: "Specialty-pharmacy and brand ops", count: 12 },
    geographies: ["Northeast", "Florida / Southeast", "Texas", "California", "Great Lakes", "Ohio Valley / Appalachia"],
    evidence: "AstraZeneca Access 360 and FASENRA 360 cover benefits, fulfillment, financial support and educational nursing services.",
    method: "Parallel allergy and pulmonology coverage with severe-asthma accounts and an EGPA referral overlay; access and nursing support remain material for biologic starts.",
    geographyMethod: "Weights allergy/pulmonology density, severe-asthma burden, large practices and biologic administration sites.",
    sources: [
      { label: "FASENRA access support", url: "https://www.myaccess360.com/patient/fasenra-benralizumab/" },
      { label: "AAAAI allergist directory", url: "https://allergist.aaaai.org/find/" },
    ],
  }),
  Fiasp: insulinModel("Fiasp", "Novo Nordisk", 70, "Fast-acting insulin with broad diabetes access; maintain device education and payer coverage but target field calls to endocrinology.", { label: "Fiasp savings and support", url: "https://www.novocare.com/diabetes/products/fiasp.html" }),
  "Follistim AQ Cartridge": fertilityModel("FOLLISTIM AQ Cartridge", "Organon", { label: "FOLLISTIM patient support", url: "https://organonpro.com/en-us/product/follistim-aq-cartridge/patient-support/" }),
  Gamifant: buildModel({
    indication: "Primary HLH and HLH/macrophage activation syndrome in Still's disease",
    confidence: "High",
    primary: { role: "Rare-hematology account managers", count: 16 },
    managers: 3,
    msls: 7,
    accounts: { role: "Transplant / HLH center accounts", count: 5 },
    access: 5,
    educators: { role: "Institutional educators", count: 4 },
    support: { role: "Gamifant Cares coordinators", count: 7 },
    medical: 3,
    operations: { role: "Inpatient/outpatient specialty ops", count: 5 },
    geographies: ["Northeast children's hospitals", "Cincinnati / Great Lakes", "Mid-Atlantic", "Atlanta / Florida", "Texas", "California", "Seattle"],
    evidence: "Sobi explicitly describes Gamifant Cares and a Field Reimbursement Team supporting inpatient and outpatient access.",
    method: "Covers pediatric hematology, rheumatology and transplant-center clusters; MSL and reimbursement ratios are high because starts are rare, urgent and institutionally complex.",
    geographyMethod: "Anchors to children's hospitals, cellular-therapy/transplant programs and academic HLH experts.",
    sources: [
      { label: "Gamifant Cares and field reimbursement", url: "https://www.gamifant.com/mas/navigating-coverage" },
      { label: "Gamifant support resources", url: "https://www.gamifant.com/mas/support-resources" },
    ],
  }),
  "GATTEX KIT": buildModel({
    indication: "Short bowel syndrome in patients dependent on parenteral support",
    confidence: "High",
    primary: { role: "Rare-GI account managers", count: 26 },
    managers: 4,
    msls: 7,
    accounts: { role: "Intestinal-rehab center accounts", count: 5 },
    access: 6,
    educators: { role: "Field nurse / injection educators", count: 8 },
    support: { role: "OnePath patient support managers", count: 11 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and home-care ops", count: 7 },
    geographies: ["Boston–New York–Philadelphia", "Cleveland–Chicago", "Pittsburgh / Mid-Atlantic", "Atlanta–Durham", "Texas", "California", "Seattle"],
    evidence: "GATTEX OnePath materials identify dedicated Patient Support Managers and home injection-training nurses.",
    method: "Territories center on intestinal-rehabilitation and nutrition-support programs; field nurses and inside coordinators are sized high for daily injection and home-care logistics.",
    geographyMethod: "Follows major intestinal-failure, transplant and home-parenteral-nutrition referral centers.",
    sources: [
      { label: "GATTEX OnePath office starter kit", url: "https://www.gattexhcp.com/Content/pdf/GATTEX_HCP_Digital_OfficeStarterKit.pdf" },
      { label: "Oley Foundation center resources", url: "https://oley.org/" },
    ],
  }),
  Genotropin: growthModel("GENOTROPIN", "Pfizer", { label: "Pfizer Bridge support", url: "https://genotropin.pfizerpro.com/support-and-services/patient-support-and-savings" }),
  "Gonal-f": fertilityModel("GONAL-f", "EMD Serono", { label: "EMD Serono fertility support", url: "https://www.emdseronofertility.com/home.html" }),
  "Gonal-f RFF RediJect": fertilityModel("GONAL-f RFF Redi-ject", "EMD Serono", { label: "EMD Serono fertility savings", url: "https://www.emdseronofertility.com/content/healthcare-hcp/emd/en/fertility/patient/affording-treatment/medication-savings.html" }),
  Hepcludex: buildModel({
    indication: "Chronic hepatitis delta virus infection",
    confidence: "High",
    primary: { role: "Hepatology / ID representatives", count: 42 },
    managers: 6,
    msls: 8,
    accounts: { role: "Liver-center / IDN accounts", count: 6 },
    access: 6,
    educators: { role: "Reconstitution / injection educators", count: 5 },
    support: { role: "Support Path navigators", count: 9 },
    medical: 3,
    operations: { role: "Specialty-pharmacy and brand ops", count: 7 },
    geographies: ["New York / New Jersey", "California", "Texas", "Florida", "Chicago", "Washington, DC / Baltimore", "Seattle"],
    evidence: "Gilead Support Path provides live navigators, benefits investigation, prior authorization/appeal information and specialty-pharmacy support for HEPCLUDEX.",
    method: "Targets transplant hepatology, viral-hepatitis and high-volume ID practices; access and injection education are significant for a newly established specialty pathway.",
    geographyMethod: "Weights chronic hepatitis burden, immigrant population, liver-transplant centers and academic viral-hepatitis programs.",
    sources: [
      { label: "HEPCLUDEX patient support", url: "https://www.hepcludexhcp.com/patient-support-program" },
      { label: "Gilead U.S. patient access", url: "https://www.gilead.com/medicines/medication-access/us-patient-access" },
    ],
  }),
  Humalog: insulinModel("Humalog", "Lilly", 72, "Broad rapid-acting insulin franchise; field calls extend beyond endocrinology only for the highest-volume integrated diabetes accounts."),
  Humatrope: buildModel({
    indication: "Pediatric and adult growth disorders; U.S. distribution scheduled to end after 2026",
    confidence: "High",
    primary: { role: "Transition account managers", count: 8 },
    managers: 2,
    msls: 3,
    accounts: { role: "Pediatric endocrine accounts", count: 3 },
    access: 2,
    educators: { role: "Device transition educators", count: 3 },
    support: { role: "Patient transition coordinators", count: 6 },
    medical: 2,
    operations: { role: "Supply wind-down and safety ops", count: 5 },
    geographies: ["National transition coverage", "Northeast", "Great Lakes", "Texas", "California", "Southeast"],
    evidence: "Lilly states it will permanently discontinue U.S. Humatrope distribution on December 31, 2026, with limited inventory thereafter.",
    method: "Modeled as a temporary patient-transition and supply-continuity organization, not a growth commercial build.",
    geographyMethod: "A national inside-led model supports current patients; field coverage is limited to high-volume pediatric endocrine centers.",
    note: "Diligence gate: treat discontinuation and remaining supply as a threshold issue before any acquisition work.",
    sources: [
      { label: "Humatrope discontinuation notice", url: "https://humatrope.lilly.com/" },
      LILLY_SUPPORT,
    ],
  }),
  "Humulin R U-500": insulinModel("Humulin R U-500", "Lilly", 58, "Concentrated insulin for highly insulin-resistant patients; emphasize endocrinology, safe dosing education and device support."),
  Ilaris: buildModel({
    indication: "Autoinflammatory periodic fever syndromes and Still's disease",
    confidence: "High",
    primary: { role: "Rare-immunology account managers", count: 34 },
    managers: 5,
    msls: 9,
    accounts: { role: "Autoinflammatory-center accounts", count: 6 },
    access: 7,
    educators: { role: "Home-injection educators", count: 7 },
    support: { role: "ILARIS Companion coordinators", count: 10 },
    medical: 4,
    operations: { role: "Medical-benefit and specialty-pharmacy ops", count: 8 },
    geographies: ["Northeast children's hospitals", "Mid-Atlantic", "Great Lakes", "Texas", "California", "Southeast", "Pacific Northwest"],
    evidence: "ILARIS Companion supports acquisition, reimbursement and optional services, including start support for a multi-indication rare-inflammatory product.",
    method: "Covers pediatric/adult rheumatology and autoinflammatory referral centers; case, access and administration support are high relative to account count.",
    geographyMethod: "Anchors to academic rheumatology, immunology and children's-hospital clusters.",
    sources: [
      { label: "ILARIS HCP access guide", url: "https://www.ilarishcp.com/sites/ilarishcp_com/files/documents/fa-11252793-pss-ila-hcp-acquisition-and-reimbursement-guide-digital-9-24.pdf" },
      { label: "Novartis patient support", url: "https://www.novartis.com/us-en/patients-and-caregivers/patient-assistance/novartis-patient-support" },
    ],
  }),
  Ilumya: buildModel({
    indication: "Moderate-to-severe plaque psoriasis",
    confidence: "High",
    primary: { role: "Dermatology sales representatives", count: 76 },
    managers: 10,
    msls: 9,
    accounts: { role: "Large dermatology-group accounts", count: 7 },
    access: 9,
    educators: { role: "Office-injection educators", count: 6 },
    support: { role: "ILUMYA Support coordinators", count: 10 },
    medical: 4,
    operations: { role: "Buy-and-bill, trade and brand ops", count: 9 },
    geographies: ["NY / NJ / PA / New England", "Florida", "Texas", "California", "Great Lakes", "Phoenix / Denver", "Pacific Northwest"],
    evidence: "ILUMYA Support and Field Reimbursement Managers address enrollment, medical-benefit access and HCP administration.",
    method: "Targets high-volume dermatology practices and psoriasis centers; buy-and-bill support and office workflow education increase account/access staffing.",
    geographyMethod: "Weights dermatologist density, large practice groups and office-administered biologic capacity.",
    sources: [
      { label: "ILUMYA access and support", url: "https://www.ilumyapro.com/access-and-support/patient-access" },
      { label: "AAD dermatologist directory", url: "https://find-a-derm-backend.aad.org/country/United%20States" },
    ],
  }),
  IMCIVREE: buildModel({
    indication: "Chronic weight management in genetically confirmed rare MC4R-pathway obesity",
    confidence: "High",
    primary: { role: "Rare-obesity account managers", count: 18 },
    managers: 3,
    msls: 7,
    accounts: { role: "Genetic-obesity center accounts", count: 4 },
    access: 6,
    educators: { role: "Patient education managers", count: 6 },
    support: { role: "Rhythm InTune access coordinators", count: 10 },
    medical: 3,
    operations: { role: "Genetic-testing and specialty-pharmacy ops", count: 7 },
    geographies: RARE_ENDOCRINE_GEOS,
    evidence: "Rhythm InTune provides access, genetic-testing support, injection training and Patient Education Managers for ongoing treatment education.",
    method: "Territories center on pediatric endocrine/genetics centers; disease identification, testing and access require more MSL, educator and coordinator capacity than sales.",
    geographyMethod: "Anchors to academic obesity-genetics and pediatric endocrine programs with national virtual coverage.",
    sources: [
      { label: "IMCIVREE prescribing and Rhythm InTune", url: "https://ppl.imcivreehcp.com/prescribing-imcivree/" },
      { label: "Rhythm InTune education guide", url: "https://www.imcivree.com/How_To_Give_IMCIVREE_Guide.pdf" },
    ],
  }),
  Increlex: growthModel("INCRELEX", "Eton", { label: "Eton Cares for INCRELEX", url: "https://increlex.com/support-resources/" }, true),
  Inmazeb: buildModel({
    indication: "Treatment of Zaire ebolavirus infection",
    confidence: "High",
    primary: { role: "Federal / global-health accounts", count: 4 },
    managers: 1,
    msls: 4,
    accounts: { role: "Government contracting / stockpile", count: 5 },
    access: 0,
    educators: { role: "Outbreak-response educators", count: 3 },
    support: { role: "Deployment coordination", count: 4 },
    medical: 3,
    operations: { role: "Stockpile, quality and logistics", count: 6 },
    geographies: FEDERAL_GEOS,
    evidence: "Regeneron reports delivery of an INMAZEB stockpile to the U.S. and government/WHO coordination for outbreak deployment.",
    method: "No conventional sales force: a compact government-account, medical and logistics organization supports procurement, readiness and rapid response.",
    geographyMethod: "Focuses on federal preparedness agencies, designated biocontainment centers and stockpile logistics nodes.",
    sources: [
      { label: "Regeneron INMAZEB stockpile update", url: "https://investor.regeneron.com/news-releases/news-release-details/regeneron-donates-ebola-treatment-use-countries-most-risk" },
      { label: "Strategic National Stockpile", url: "https://www.aspr.gov/readiness-response/medical-countermeasures-biodefense/sns/stockpile-products" },
    ],
  }),
  Jeuveau: buildModel({
    indication: "Temporary improvement of moderate-to-severe glabellar lines in adults",
    confidence: "Medium",
    primary: { role: "Aesthetic practice managers", count: 104 },
    managers: 13,
    msls: 5,
    accounts: { role: "National aesthetic accounts", count: 8 },
    access: 0,
    educators: { role: "Clinical / injection trainers", count: 14 },
    support: { role: "Practice and consumer-program support", count: 12 },
    medical: 4,
    operations: { role: "Loyalty, digital, trade and analytics", count: 14 },
    geographies: ["Southern California", "New York / New Jersey", "Miami / South Florida", "Texas triangle", "Atlanta", "Chicago", "Phoenix / Scottsdale", "Las Vegas"],
    evidence: "Evolus describes a self-pay, customer-centric commercial model built around licensed aesthetic practitioners and practice-enhancing programs.",
    method: "Territories cover high-volume injectors and med-spa groups; practice development, training and consumer loyalty replace reimbursement and patient-hub roles.",
    geographyMethod: "Weights aesthetic-injector density, self-pay spending and high-growth cosmetic markets.",
    sources: [
      { label: "Evolus commercial model", url: "https://investors.evolus.com/overview/" },
      { label: "Jeuveau professional site", url: "https://www.evolus.com/" },
    ],
  }),
  Kalbitor: buildModel({
    indication: "Acute attacks of hereditary angioedema",
    confidence: "High",
    primary: { role: "HAE account managers", count: 14 },
    managers: 3,
    msls: 6,
    accounts: { role: "HAE-center / treatment-site accounts", count: 4 },
    access: 4,
    educators: { role: "Administration / safety educators", count: 5 },
    support: { role: "Takeda Patient Support coordinators", count: 7 },
    medical: 3,
    operations: { role: "Specialty distribution and brand ops", count: 5 },
    geographies: ["Northeast HAE centers", "Mid-Atlantic", "Great Lakes", "Southeast", "Texas", "California", "Pacific Northwest"],
    evidence: "KALBITOR must be administered by an equipped healthcare professional because of anaphylaxis risk; Takeda Patient Support manages product access.",
    method: "A small rare-disease team covers HAE centers and qualified treatment sites; medical, safety education and distribution roles are high relative to sales.",
    geographyMethod: "Follows HAE specialist centers and major allergy/immunology referral markets.",
    sources: [
      { label: "KALBITOR HCP and support model", url: "https://www.kalbitor.com/hcp" },
      { label: "HAEA treatment-center finder", url: "https://www.haea.org/pages/p/treatment-centers" },
    ],
  }),
  Kepivance: buildModel({
    indication: "Reduction of severe oral mucositis in selected hematologic cancer regimens",
    confidence: "Directional",
    primary: { role: "Transplant-center account managers", count: 8 },
    managers: 2,
    msls: 4,
    accounts: { role: "National transplant accounts", count: 3 },
    access: 1,
    educators: { role: "Supportive-care educators", count: 3 },
    support: { role: "Order support", count: 3 },
    medical: 3,
    operations: { role: "Hospital distribution and safety ops", count: 4 },
    geographies: ["Northeast transplant centers", "Mid-Atlantic", "Great Lakes", "Texas", "California", "Seattle", "Southeast"],
    evidence: "Sobi positions KEPIVANCE as a specialty-care product ordered through a small set of hospital distributors, with no broad patient program disclosed.",
    method: "A compact transplant-account and medical team covers high-volume hematopoietic stem-cell transplant programs; central ordering replaces field access scale.",
    geographyMethod: "Anchors to major hematopoietic stem-cell transplant and academic hematology centers.",
    sources: [
      { label: "KEPIVANCE ordering model", url: "https://www.kepivance.com/" },
      { label: "Sobi U.S. medicines", url: "https://www.sobi.com/usa/cs/node/4700" },
    ],
  }),
  Kesimpta: buildModel({
    indication: "Relapsing forms of multiple sclerosis",
    confidence: "High",
    primary: { role: "MS sales representatives", count: 90 },
    managers: 11,
    msls: 14,
    accounts: { role: "MS-center / IDN accounts", count: 8 },
    access: 10,
    educators: { role: "Injection educators", count: 7 },
    support: { role: "Patient access coordinators", count: 16 },
    medical: 5,
    operations: { role: "Specialty-pharmacy and brand ops", count: 12 },
    geographies: MS_GEOS,
    evidence: "Novartis Patient Support for KESIMPTA explicitly includes Access Reimbursement Managers, Patient Access Coordinators and single points of contact for offices and patients.",
    method: "Broad MS-center and community-neurology coverage with national access and pharmacy operations; self-injection requires less field nursing than older injectable platforms.",
    geographyMethod: "Weights MS-center density, neurologist concentration and large insured populations.",
    sources: [
      { label: "KESIMPTA coverage and support", url: "https://www.kesimptahcp.com/starting-patients/coverage-support" },
      { label: "Consortium of MS Centers", url: "https://www.mscare.org/page/clinic_directory" },
    ],
  }),
};
