import type { AssetDiligence, DiligenceSource } from "./diligence";

type ScreenProduct = { id: string; company: string; marketStatus: string };
type Ownership = "Public parent" | "Private";
type Profile = { terms: string[]; ownership: Ownership; parent: string; ticker?: string; url: string };

function p(terms: string, ownership: Ownership, parent: string, ticker: string | undefined, url: string): Profile {
  return { terms: terms.split("|"), ownership, parent, ticker, url };
}

const profiles: Profile[] = [
  p("AZURITY", "Private", "Azurity Pharmaceuticals, Inc.", undefined, "https://azurity.com/"),
  p("ENDO OPERATIONS|MALLINCKRODT", "Private", "Keenova Therapeutics / Par Health", undefined, "https://www.mallinckrodt.com/"),
  p("COSETTE PHARMACEUTICALS", "Private", "Cosette Pharmaceuticals, Inc.", undefined, "https://cosettepharma.com/"),
  p("AMICUS THERAPEUTICS", "Public parent", "Amicus Therapeutics, Inc.", "NASDAQ: FOLD", "https://www.amicusrx.com/"),
  p("AMNEAL", "Public parent", "Amneal Pharmaceuticals, Inc.", "NASDAQ: AMRX", "https://amneal.com/"),
  p("EMERGENT", "Public parent", "Emergent BioSolutions Inc.", "NYSE: EBS", "https://www.emergentbiosolutions.com/"),
  p("CHEPLAPHARM", "Private", "CHEPLAPHARM Arzneimittel GmbH", undefined, "https://www.cheplapharm.com/"),
  p("HELSINN", "Private", "Helsinn Healthcare SA", undefined, "https://www.helsinn.com/"),
  p("SENTYNL", "Public parent", "Zydus Lifesciences Limited", "NSE: ZYDUSLIFE", "https://sentynl.com/"),
  p("TERSERA", "Private", "TerSera Therapeutics LLC", undefined, "https://www.tersera.com/"),
  p("THEA PHARMA", "Private", "Laboratoires Théa", undefined, "https://www.theapharmaceuticals.com/"),
  p("BIOXCEL", "Public parent", "BioXcel Therapeutics, Inc.", "NASDAQ: BTAI", "https://www.bioxceltherapeutics.com/"),
  p("AVEO PHARMACEUTICALS", "Public parent", "LG Chem Ltd.", "KRX: 051910", "https://www.aveooncology.com/"),
  p("AYTU", "Public parent", "Aytu BioPharma, Inc.", "NASDAQ: AYTU", "https://aytubio.com/"),
  p("DOMPÉ", "Private", "Dompé farmaceutici S.p.A.", undefined, "https://www.dompe.com/"),
  p("EMD SERONO", "Public parent", "Merck KGaA", "Frankfurt: MRK", "https://www.emdgroup.com/"),
  p("MERCK SHARP|MERCK & CO", "Public parent", "Merck & Co., Inc.", "NYSE: MRK", "https://www.merck.com/"),
  p("PFIZER|AMERICAN CYANAMID", "Public parent", "Pfizer Inc.", "NYSE: PFE", "https://www.pfizer.com/"),
  p("ABBVIE", "Public parent", "AbbVie Inc.", "NYSE: ABBV", "https://www.abbvie.com/"),
  p("BAXTER", "Public parent", "Baxter International Inc.", "NYSE: BAX", "https://www.baxter.com/"),
  p("AMGEN", "Public parent", "Amgen Inc.", "NASDAQ: AMGN", "https://www.amgen.com/"),
  p("ELI LILLY", "Public parent", "Eli Lilly and Company", "NYSE: LLY", "https://www.lilly.com/"),
  p("VIIV HEALTHCARE|GLAXOSMITHKLINE|GLAXO GROUP", "Public parent", "GSK plc", "NYSE: GSK", "https://us.gsk.com/"),
  p("BOEHRINGER INGELHEIM", "Private", "Boehringer Ingelheim", undefined, "https://www.boehringer-ingelheim.com/us"),
  p("HARROW EYE", "Public parent", "Harrow, Inc.", "NASDAQ: HROW", "https://www.harrow.com/"),
  p("B BRAUN", "Private", "B. Braun SE", undefined, "https://www.bbraunusa.com/"),
  p("GENENTECH", "Public parent", "Roche Holding AG", "SIX: ROG", "https://www.gene.com/"),
  p("GILEAD", "Public parent", "Gilead Sciences, Inc.", "NASDAQ: GILD", "https://www.gilead.com/"),
  p("HIKMA", "Public parent", "Hikma Pharmaceuticals PLC", "LSE: HIK", "https://www.hikma.com/"),
  p("JANSSEN|JOHNSON & JOHNSON", "Public parent", "Johnson & Johnson", "NYSE: JNJ", "https://www.jnj.com/innovativemedicine"),
  p("NOVARTIS", "Public parent", "Novartis AG", "NYSE: NVS", "https://www.novartis.com/us-en/"),
  p("NOVO NORDISK", "Public parent", "Novo Nordisk A/S", "NYSE: NVO", "https://www.novonordisk-us.com/"),
  p("ALCON", "Public parent", "Alcon Inc.", "NYSE: ALC", "https://www.alcon.com/"),
  p("BAYER", "Public parent", "Bayer AG", "XETRA: BAYN", "https://www.bayer.com/en/us/united-states"),
  p("FRESENIUS KABI", "Public parent", "Fresenius SE & Co. KGaA", "Frankfurt: FRE", "https://www.fresenius-kabi.com/us"),
  p("REGENERON", "Public parent", "Regeneron Pharmaceuticals, Inc.", "NASDAQ: REGN", "https://www.regeneron.com/"),
  p("SANOFI|ABLYNX", "Public parent", "Sanofi S.A.", "NASDAQ: SNY", "https://www.sanofi.us/"),
  p("TAKEDA", "Public parent", "Takeda Pharmaceutical Company Limited", "NYSE: TAK", "https://www.takeda.com/en-us/"),
  p("VERTEX", "Public parent", "Vertex Pharmaceuticals Incorporated", "NASDAQ: VRTX", "https://www.vrtx.com/"),
  p("ALMATICA", "Private", "Almatica Pharma LLC", undefined, "https://www.almatica.com/"),
  p("BAUSCH AND LOMB", "Public parent", "Bausch + Lomb Corporation", "NYSE: BLCO", "https://www.bausch.com/"),
  p("BAUSCH HEALTH|SALIX PHARMACEUTICALS", "Public parent", "Bausch Health Companies Inc.", "NYSE: BHC", "https://www.bauschhealth.com/"),
  p("CHIESI", "Private", "Chiesi Farmaceutici S.p.A.", undefined, "https://www.chiesiusa.com/"),
  p("ETON PHARMACEUTICALS", "Public parent", "Eton Pharmaceuticals, Inc.", "NASDAQ: ETON", "https://www.etonpharma.com/"),
  p("ORGANON", "Public parent", "Organon & Co.", "NYSE: OGN", "https://www.organon.com/"),
  p("SWEDISH ORPHAN BIOVITRUM", "Public parent", "Swedish Orphan Biovitrum AB", "Nasdaq Stockholm: SOBI", "https://www.sobi.com/en/united-states"),
  p("ALKERMES", "Public parent", "Alkermes plc", "NASDAQ: ALKS", "https://www.alkermes.com/"),
  p("ALNYLAM", "Public parent", "Alnylam Pharmaceuticals, Inc.", "NASDAQ: ALNY", "https://www.alnylam.com/"),
  p("ASTRAZENECA|ALEXION", "Public parent", "AstraZeneca PLC", "NASDAQ: AZN", "https://www.astrazeneca-us.com/"),
  p("BRISTOL MYERS|BRISTOL-MYERS|APOTHECON", "Public parent", "Bristol Myers Squibb", "NYSE: BMY", "https://www.bms.com/"),
  p("CUMBERLAND", "Public parent", "Cumberland Pharmaceuticals Inc.", "NASDAQ: CPIX", "https://www.cumberlandpharma.com/"),
  p("CYCLE PHARMACEUTICALS", "Private", "Cycle Pharmaceuticals Ltd.", undefined, "https://www.cyclepharma.com/"),
  p("ESTEVE", "Private", "ESTEVE Pharmaceuticals", undefined, "https://www.esteve.com/"),
  p("HERON THERAPEUTICS", "Public parent", "Heron Therapeutics, Inc.", "NASDAQ: HRTX", "https://www.herontx.com/"),
  p("IBSA", "Private", "IBSA Institut Biochimique SA", undefined, "https://www.ibsausa.com/"),
  p("PHATHOM", "Public parent", "Phathom Pharmaceuticals, Inc.", "NASDAQ: PHAT", "https://www.phathompharma.com/"),
  p("RECORDATI", "Public parent", "Recordati S.p.A.", "BIT: REC", "https://recordatirarediseases.com/"),
  p("SAREPTA", "Public parent", "Sarepta Therapeutics, Inc.", "NASDAQ: SRPT", "https://www.sarepta.com/"),
  p("SUN PHARMA|SUN PHARMACEUTICAL", "Public parent", "Sun Pharmaceutical Industries Ltd.", "NSE: SUNPHARMA", "https://sunpharma.com/usa/"),
  p("THERATECHNOLOGIES", "Private", "Future Pak, LLC", undefined, "https://www.theratech.com/"),
  p("UNITED THERAPEUTICS", "Public parent", "United Therapeutics Corporation", "NASDAQ: UTHR", "https://www.unither.com/"),
  p("VIATRIS|MYLAN", "Public parent", "Viatris Inc.", "NASDAQ: VTRS", "https://www.viatris.com/"),
  p("XERIS", "Public parent", "Xeris Biopharma Holdings, Inc.", "NASDAQ: XERS", "https://www.xerispharma.com/"),
  p("ZYDUS", "Public parent", "Zydus Lifesciences Limited", "NSE: ZYDUSLIFE", "https://www.zyduslife.com/"),
  p("AMPHASTAR", "Public parent", "Amphastar Pharmaceuticals, Inc.", "NASDAQ: AMPH", "https://www.amphastar.com/"),
  p("ANI PHARMACEUTICALS", "Public parent", "ANI Pharmaceuticals, Inc.", "NASDAQ: ANIP", "https://www.anipharmaceuticals.com/"),
  p("APELLIS", "Public parent", "Apellis Pharmaceuticals, Inc.", "NASDAQ: APLS", "https://apellis.com/"),
  p("ARDELYX", "Public parent", "Ardelyx, Inc.", "NASDAQ: ARDX", "https://www.ardelyx.com/"),
  p("AXSOME", "Public parent", "Axsome Therapeutics, Inc.", "NASDAQ: AXSM", "https://www.axsome.com/"),
  p("BIOCRYST", "Public parent", "BioCryst Pharmaceuticals, Inc.", "NASDAQ: BCRX", "https://www.biocryst.com/"),
  p("BIOGEN", "Public parent", "Biogen Inc.", "NASDAQ: BIIB", "https://www.biogen.com/"),
  p("COLLEGIUM", "Public parent", "Collegium Pharmaceutical, Inc.", "NASDAQ: COLL", "https://www.collegiumpharma.com/"),
  p("ESPERION", "Public parent", "Esperion Therapeutics, Inc.", "NASDAQ: ESPR", "https://www.esperion.com/"),
  p("GALDERMA", "Public parent", "Galderma Group AG", "SIX: GALD", "https://www.galderma.com/us"),
  p("INDIVIOR", "Public parent", "Indivior PLC", "NASDAQ: INDV", "https://www.indivior.com/"),
  p("SUMITOMO PHARMA", "Public parent", "Sumitomo Pharma Co., Ltd.", "TSE: 4506", "https://www.sumitomo-pharma.com/"),
  p("TEVA", "Public parent", "Teva Pharmaceutical Industries Ltd.", "NYSE: TEVA", "https://www.tevausa.com/"),
  p("UCB", "Public parent", "UCB S.A.", "Euronext: UCB", "https://www.ucb-usa.com/"),
  p("VANDA", "Public parent", "Vanda Pharmaceuticals Inc.", "NASDAQ: VNDA", "https://www.vandapharma.com/"),
  p("AFT PHARMACEUTICALS", "Public parent", "AFT Pharmaceuticals Limited", "NZX/ASX: AFT", "https://www.aftpharm.com/"),
  p("AKEBIA", "Public parent", "Akebia Therapeutics, Inc.", "NASDAQ: AKBA", "https://www.akebia.com/"),
  p("ARCUTIS", "Public parent", "Arcutis Biotherapeutics, Inc.", "NASDAQ: ARQT", "https://www.arcutis.com/"),
  p("ARS PHARMACEUTICALS", "Public parent", "ARS Pharmaceuticals, Inc.", "NASDAQ: SPRY", "https://www.ars-pharma.com/"),
  p("AVADEL", "Public parent", "Avadel Pharmaceuticals plc", "NASDAQ: AVDL", "https://www.avadel.com/"),
  p("BRAEBURN", "Private", "Braeburn, Inc.", undefined, "https://braeburnrx.com/"),
  p("CATALYST PHARMACEUTICALS", "Public parent", "Catalyst Pharmaceuticals, Inc.", "NASDAQ: CPRX", "https://catalystpharma.com/"),
  p("CELLTRION", "Public parent", "Celltrion, Inc.", "KRX: 068270", "https://www.celltrion.com/en-us"),
  p("CLINUVEL", "Public parent", "Clinuvel Pharmaceuticals Ltd.", "ASX: CUV", "https://www.clinuvel.com/"),
  p("COOPERSURGICAL", "Public parent", "The Cooper Companies, Inc.", "NASDAQ: COO", "https://www.coopersurgical.com/"),
  p("CORMEDIX", "Public parent", "CorMedix Inc.", "NASDAQ: CRMD", "https://cormedix.com/"),
  p("CSL", "Public parent", "CSL Limited", "ASX: CSL", "https://www.csl.com/"),
  p("DAIICHI SANKYO", "Public parent", "Daiichi Sankyo Company, Limited", "TSE: 4568", "https://www.daiichisankyo.com/us/"),
  p("DR REDDYS", "Public parent", "Dr. Reddy's Laboratories Limited", "NYSE: RDY", "https://www.drreddys.com/"),
  p("EISAI", "Public parent", "Eisai Co., Ltd.", "TSE: 4523", "https://www.eisai.com/us"),
  p("EVOLUS", "Public parent", "Evolus, Inc.", "NASDAQ: EOLS", "https://www.evolus.com/"),
  p("EYEPOINT", "Public parent", "EyePoint Pharmaceuticals, Inc.", "NASDAQ: EYPT", "https://www.eyepointpharma.com/"),
  p("FERRING", "Private", "Ferring Pharmaceuticals", undefined, "https://www.ferringusa.com/"),
  p("GLAUKOS", "Public parent", "Glaukos Corporation", "NYSE: GKOS", "https://www.glaukos.com/"),
  p("GLENMARK", "Public parent", "Glenmark Pharmaceuticals Limited", "NSE: GLENMARK", "https://glenmarkpharma-us.com/"),
  p("HALOZYME", "Public parent", "Halozyme Therapeutics, Inc.", "NASDAQ: HALO", "https://halozyme.com/"),
  p("HARMONY BIOSCIENCES", "Public parent", "Harmony Biosciences Holdings, Inc.", "NASDAQ: HRMY", "https://www.harmonybiosciences.com/"),
  p("HISAMITSU|NOVEN PHARMACEUTICALS", "Public parent", "Hisamitsu Pharmaceutical Co., Inc.", "TSE: 4530", "https://global.hisamitsu/"),
  p("INCYTE", "Public parent", "Incyte Corporation", "NASDAQ: INCY", "https://www.incyte.com/"),
  p("ITERUM", "Public parent", "Iterum Therapeutics plc", "NASDAQ: ITRM", "https://www.iterumtx.com/"),
  p("JAZZ PHARMACEUTICALS", "Public parent", "Jazz Pharmaceuticals plc", "NASDAQ: JAZZ", "https://www.jazzpharma.com/"),
  p("KYOWA KIRIN", "Public parent", "Kyowa Kirin Co., Ltd.", "TSE: 4151", "https://www.kyowakirin.com/usa/"),
  p("LEXICON", "Public parent", "Lexicon Pharmaceuticals, Inc.", "NASDAQ: LXRX", "https://www.lexpharma.com/"),
  p("LIQUIDIA", "Public parent", "Liquidia Corporation", "NASDAQ: LQDA", "https://www.liquidia.com/"),
  p("MANNKIND", "Public parent", "MannKind Corporation", "NASDAQ: MNKD", "https://www.mannkindcorp.com/"),
  p("MEDICURE", "Public parent", "Medicure Inc.", "TSXV: MPH", "https://www.medicure.com/"),
  p("NIPPON SHINYAKU", "Public parent", "Nippon Shinyaku Co., Ltd.", "TSE: 4516", "https://www.nippon-shinyaku.co.jp/english/"),
  p("OCULAR THERAPEUTIX", "Public parent", "Ocular Therapeutix, Inc.", "NASDAQ: OCUL", "https://www.ocutx.com/"),
  p("OTSUKA", "Public parent", "Otsuka Holdings Co., Ltd.", "TSE: 4578", "https://www.otsuka-us.com/"),
  p("PACIRA", "Public parent", "Pacira BioSciences, Inc.", "NASDAQ: PCRX", "https://www.pacira.com/"),
  p("RHYTHM PHARMACEUTICALS", "Public parent", "Rhythm Pharmaceuticals, Inc.", "NASDAQ: RYTM", "https://www.rhythmtx.com/"),
  p("SANDOZ", "Public parent", "Sandoz Group AG", "SIX: SDZ", "https://www.sandoz.com/"),
  p("SCILEX", "Public parent", "Scilex Holding Company", "NASDAQ: SCLX", "https://www.scilexholding.com/"),
  p("SCPHARMACEUTICALS", "Public parent", "scPharmaceuticals Inc.", "NASDAQ: SCPH", "https://www.scpharmaceuticals.com/"),
  p("SHIONOGI", "Public parent", "Shionogi & Co., Ltd.", "TSE: 4507", "https://www.shionogi.com/us/en/"),
  p("SIGA TECHNOLOGIES", "Public parent", "SIGA Technologies, Inc.", "NASDAQ: SIGA", "https://www.siga.com/"),
  p("SOLENO", "Public parent", "Soleno Therapeutics, Inc.", "NASDAQ: SLNO", "https://soleno.life/"),
  p("SUPERNUS", "Public parent", "Supernus Pharmaceuticals, Inc.", "NASDAQ: SUPN", "https://www.supernus.com/"),
  p("TONIX", "Public parent", "Tonix Pharmaceuticals Holding Corp.", "NASDAQ: TNXP", "https://www.tonixpharma.com/"),
  p("WOCKHARDT", "Public parent", "Wockhardt Limited", "NSE: WOCKPHARMA", "https://www.wockhardt.com/"),
];

function regulatorySource(product: ScreenProduct): DiligenceSource {
  return product.id.startsWith("BLA-")
    ? { id: "fda-listing", label: "FDA Purple Book", url: "https://purplebooksearch.fda.gov/" }
    : { id: "fda-listing", label: "FDA Orange Book", url: "https://www.fda.gov/drugs/drug-approvals-and-databases/approved-drug-products-therapeutic-equivalence-evaluations-orange-book" };
}

export function universeDiligence(product: ScreenProduct): AssetDiligence {
  const company = product.company.toUpperCase();
  const profile = profiles.find((item) => item.terms.some((term) => company.includes(term)));
  const listing = regulatorySource(product);
  return {
    ownership: profile?.ownership ?? "Not verified",
    parent: profile?.parent ?? "Controlling parent not verified",
    rightsHolder: product.company,
    holderBasis: "FDA application holder",
    ticker: profile?.ticker,
    companyUrl: profile?.url ?? listing.url,
    latestDisplay: "Not separately disclosed",
    latestPeriod: "Public product-level annual revenue",
    sortUsdMm: null,
    disclosure: "Not disclosed",
    launch: product.marketStatus,
    indicationSplit: "No indication-level revenue split attached to this screen-level record.",
    revenueFacts: [],
    notes: [
      profile
        ? "Ownership is mapped from the FDA-listed application holder to its controlling corporate group; current asset-level commercial rights should be confirmed."
        : "The FDA-listed application holder is shown. Current controlling parent and asset-level commercial rights have not been verified.",
      "No product-level annual revenue fact is attached to this record; no estimate is shown.",
    ],
    sources: profile ? [{ id: "owner-site", label: `${profile.parent} corporate site`, url: profile.url }, listing] : [listing],
  };
}
